/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateGuestFirewallRuleRequest,
  Envelope,
  SetGuestFirewallOptionsRequest,
} from '../models/index';
import {
    CreateGuestFirewallRuleRequestFromJSON,
    CreateGuestFirewallRuleRequestToJSON,
    EnvelopeFromJSON,
    EnvelopeToJSON,
    SetGuestFirewallOptionsRequestFromJSON,
    SetGuestFirewallOptionsRequestToJSON,
} from '../models/index';

export interface CreateGuestFirewallRuleOperationRequest {
    hostId: number;
    type: CreateGuestFirewallRuleOperationTypeEnum;
    vmid: number;
    createGuestFirewallRuleRequest: CreateGuestFirewallRuleRequest;
}

export interface DeleteGuestFirewallRuleRequest {
    hostId: number;
    type: DeleteGuestFirewallRuleTypeEnum;
    vmid: number;
    ruleId: number;
    node?: string;
}

export interface GetGuestFirewallOptionsRequest {
    hostId: number;
    type: GetGuestFirewallOptionsTypeEnum;
    vmid: number;
    node?: string;
}

export interface ListGuestFirewallRulesRequest {
    hostId: number;
    type: ListGuestFirewallRulesTypeEnum;
    vmid: number;
    node?: string;
}

export interface SetGuestFirewallOptionsOperationRequest {
    hostId: number;
    type: SetGuestFirewallOptionsOperationTypeEnum;
    vmid: number;
    setGuestFirewallOptionsRequest: SetGuestFirewallOptionsRequest;
}

/**
 * 
 */
export class FirewallApi extends runtime.BaseAPI {

    /**
     * Persists a rule and reconciles it to the guest\'s PVE firewall (best-effort).
     * Add a per-guest firewall rule
     */
    async createGuestFirewallRuleRaw(requestParameters: CreateGuestFirewallRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling createGuestFirewallRule().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling createGuestFirewallRule().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling createGuestFirewallRule().'
            );
        }

        if (requestParameters['createGuestFirewallRuleRequest'] == null) {
            throw new runtime.RequiredError(
                'createGuestFirewallRuleRequest',
                'Required parameter "createGuestFirewallRuleRequest" was null or undefined when calling createGuestFirewallRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/firewall/rules`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateGuestFirewallRuleRequestToJSON(requestParameters['createGuestFirewallRuleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Persists a rule and reconciles it to the guest\'s PVE firewall (best-effort).
     * Add a per-guest firewall rule
     */
    async createGuestFirewallRule(requestParameters: CreateGuestFirewallRuleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.createGuestFirewallRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a per-guest firewall rule
     */
    async deleteGuestFirewallRuleRaw(requestParameters: DeleteGuestFirewallRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling deleteGuestFirewallRule().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling deleteGuestFirewallRule().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling deleteGuestFirewallRule().'
            );
        }

        if (requestParameters['ruleId'] == null) {
            throw new runtime.RequiredError(
                'ruleId',
                'Required parameter "ruleId" was null or undefined when calling deleteGuestFirewallRule().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/firewall/rules/{ruleId}`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));
        urlPath = urlPath.replace(`{${"ruleId"}}`, encodeURIComponent(String(requestParameters['ruleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Delete a per-guest firewall rule
     */
    async deleteGuestFirewallRule(requestParameters: DeleteGuestFirewallRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.deleteGuestFirewallRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get per-guest firewall options
     */
    async getGuestFirewallOptionsRaw(requestParameters: GetGuestFirewallOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling getGuestFirewallOptions().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling getGuestFirewallOptions().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling getGuestFirewallOptions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/firewall/options`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Get per-guest firewall options
     */
    async getGuestFirewallOptions(requestParameters: GetGuestFirewallOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.getGuestFirewallOptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List per-guest firewall rules
     */
    async listGuestFirewallRulesRaw(requestParameters: ListGuestFirewallRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling listGuestFirewallRules().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling listGuestFirewallRules().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling listGuestFirewallRules().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/firewall/rules`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * List per-guest firewall rules
     */
    async listGuestFirewallRules(requestParameters: ListGuestFirewallRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.listGuestFirewallRulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set per-guest firewall options
     */
    async setGuestFirewallOptionsRaw(requestParameters: SetGuestFirewallOptionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling setGuestFirewallOptions().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling setGuestFirewallOptions().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling setGuestFirewallOptions().'
            );
        }

        if (requestParameters['setGuestFirewallOptionsRequest'] == null) {
            throw new runtime.RequiredError(
                'setGuestFirewallOptionsRequest',
                'Required parameter "setGuestFirewallOptionsRequest" was null or undefined when calling setGuestFirewallOptions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/firewall/options`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetGuestFirewallOptionsRequestToJSON(requestParameters['setGuestFirewallOptionsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Set per-guest firewall options
     */
    async setGuestFirewallOptions(requestParameters: SetGuestFirewallOptionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.setGuestFirewallOptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreateGuestFirewallRuleOperationTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type CreateGuestFirewallRuleOperationTypeEnum = typeof CreateGuestFirewallRuleOperationTypeEnum[keyof typeof CreateGuestFirewallRuleOperationTypeEnum];
/**
 * @export
 */
export const DeleteGuestFirewallRuleTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type DeleteGuestFirewallRuleTypeEnum = typeof DeleteGuestFirewallRuleTypeEnum[keyof typeof DeleteGuestFirewallRuleTypeEnum];
/**
 * @export
 */
export const GetGuestFirewallOptionsTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type GetGuestFirewallOptionsTypeEnum = typeof GetGuestFirewallOptionsTypeEnum[keyof typeof GetGuestFirewallOptionsTypeEnum];
/**
 * @export
 */
export const ListGuestFirewallRulesTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type ListGuestFirewallRulesTypeEnum = typeof ListGuestFirewallRulesTypeEnum[keyof typeof ListGuestFirewallRulesTypeEnum];
/**
 * @export
 */
export const SetGuestFirewallOptionsOperationTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type SetGuestFirewallOptionsOperationTypeEnum = typeof SetGuestFirewallOptionsOperationTypeEnum[keyof typeof SetGuestFirewallOptionsOperationTypeEnum];
