/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AssignGuestIpRequest,
  CreateGuest200Response,
  CreateSnapshotRequest,
  Envelope,
  GetGuest200Response,
  GetNodeUsage200Response,
  GuestCreateRequest,
  ListGuests200Response,
  PowerGuestRequest,
  ReinstallGuestRequest,
  ResizeGuestRequest,
  RollbackSnapshotRequest,
  SetGuestIpFilterRequest,
  SetGuestIpconfigRequest,
  SetGuestPassword200Response,
  SetGuestPasswordRequest,
} from '../models/index';
import {
    AssignGuestIpRequestFromJSON,
    AssignGuestIpRequestToJSON,
    CreateGuest200ResponseFromJSON,
    CreateGuest200ResponseToJSON,
    CreateSnapshotRequestFromJSON,
    CreateSnapshotRequestToJSON,
    EnvelopeFromJSON,
    EnvelopeToJSON,
    GetGuest200ResponseFromJSON,
    GetGuest200ResponseToJSON,
    GetNodeUsage200ResponseFromJSON,
    GetNodeUsage200ResponseToJSON,
    GuestCreateRequestFromJSON,
    GuestCreateRequestToJSON,
    ListGuests200ResponseFromJSON,
    ListGuests200ResponseToJSON,
    PowerGuestRequestFromJSON,
    PowerGuestRequestToJSON,
    ReinstallGuestRequestFromJSON,
    ReinstallGuestRequestToJSON,
    ResizeGuestRequestFromJSON,
    ResizeGuestRequestToJSON,
    RollbackSnapshotRequestFromJSON,
    RollbackSnapshotRequestToJSON,
    SetGuestIpFilterRequestFromJSON,
    SetGuestIpFilterRequestToJSON,
    SetGuestIpconfigRequestFromJSON,
    SetGuestIpconfigRequestToJSON,
    SetGuestPassword200ResponseFromJSON,
    SetGuestPassword200ResponseToJSON,
    SetGuestPasswordRequestFromJSON,
    SetGuestPasswordRequestToJSON,
} from '../models/index';

export interface AssignGuestIpOperationRequest {
    hostId: number;
    type: AssignGuestIpOperationTypeEnum;
    vmid: number;
    assignGuestIpRequest: AssignGuestIpRequest;
}

export interface CreateGuestRequest {
    hostId: number;
    guestCreateRequest: GuestCreateRequest;
}

export interface CreateSnapshotOperationRequest {
    hostId: number;
    type: CreateSnapshotOperationTypeEnum;
    vmid: number;
    createSnapshotRequest: CreateSnapshotRequest;
}

export interface DeleteGuestRequest {
    hostId: number;
    type: DeleteGuestTypeEnum;
    vmid: number;
    node: string;
}

export interface DeleteSnapshotRequest {
    hostId: number;
    type: DeleteSnapshotTypeEnum;
    vmid: number;
    name: string;
    node?: string;
}

export interface GetGuestRequest {
    hostId: number;
    type: GetGuestTypeEnum;
    vmid: number;
}

export interface GetGuestIpFilterRequest {
    hostId: number;
    type: GetGuestIpFilterTypeEnum;
    vmid: number;
    node?: string;
}

export interface GetGuestUsageRequest {
    hostId: number;
    type: GetGuestUsageTypeEnum;
    vmid: number;
    node: string;
    range?: GetGuestUsageRangeEnum;
    metrics?: string;
}

export interface ListGuestEventsRequest {
    hostId: number;
    type: ListGuestEventsTypeEnum;
    vmid: number;
    page?: number;
    perPage?: number;
}

export interface ListGuestIpsRequest {
    hostId: number;
    type: ListGuestIpsTypeEnum;
    vmid: number;
}

export interface ListGuestsRequest {
    hostId: number;
    node?: string;
    type?: ListGuestsTypeEnum;
    status?: string;
    page?: number;
    perPage?: number;
}

export interface ListSnapshotsRequest {
    hostId: number;
    type: ListSnapshotsTypeEnum;
    vmid: number;
    node?: string;
}

export interface PowerGuestOperationRequest {
    hostId: number;
    type: PowerGuestOperationTypeEnum;
    vmid: number;
    powerGuestRequest: PowerGuestRequest;
}

export interface ReinstallGuestOperationRequest {
    hostId: number;
    type: ReinstallGuestOperationTypeEnum;
    vmid: number;
    reinstallGuestRequest: ReinstallGuestRequest;
}

export interface ResizeGuestOperationRequest {
    hostId: number;
    type: ResizeGuestOperationTypeEnum;
    vmid: number;
    resizeGuestRequest: ResizeGuestRequest;
}

export interface RollbackSnapshotOperationRequest {
    hostId: number;
    type: RollbackSnapshotOperationTypeEnum;
    vmid: number;
    name: string;
    rollbackSnapshotRequest: RollbackSnapshotRequest;
}

export interface SetGuestIpFilterOperationRequest {
    hostId: number;
    type: SetGuestIpFilterOperationTypeEnum;
    vmid: number;
    setGuestIpFilterRequest: SetGuestIpFilterRequest;
}

export interface SetGuestIpconfigOperationRequest {
    hostId: number;
    type: SetGuestIpconfigOperationTypeEnum;
    vmid: number;
    setGuestIpconfigRequest: SetGuestIpconfigRequest;
}

export interface SetGuestPasswordOperationRequest {
    hostId: number;
    type: SetGuestPasswordOperationTypeEnum;
    vmid: number;
    setGuestPasswordRequest: SetGuestPasswordRequest;
}

export interface UnassignGuestIpRequest {
    hostId: number;
    type: UnassignGuestIpTypeEnum;
    vmid: number;
    ipId: number;
}

/**
 * 
 */
export class GuestsApi extends runtime.BaseAPI {

    /**
     * Binds an unassigned IP address row (`ip_id`) to the guest and re-syncs the anti-spoof allow-list. The IP must belong to the same host.
     * Assign an IP to the guest
     */
    async assignGuestIpRaw(requestParameters: AssignGuestIpOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling assignGuestIp().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling assignGuestIp().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling assignGuestIp().'
            );
        }

        if (requestParameters['assignGuestIpRequest'] == null) {
            throw new runtime.RequiredError(
                'assignGuestIpRequest',
                'Required parameter "assignGuestIpRequest" was null or undefined when calling assignGuestIp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/ips`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssignGuestIpRequestToJSON(requestParameters['assignGuestIpRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Binds an unassigned IP address row (`ip_id`) to the guest and re-syncs the anti-spoof allow-list. The IP must belong to the same host.
     * Assign an IP to the guest
     */
    async assignGuestIp(requestParameters: AssignGuestIpOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.assignGuestIpRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a QEMU VM or an LXC container. Creation is asynchronous: this call validates the request, enqueues a provisioning job, and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{hostId}/jobs/{jobId}` until `data.status` is `done` or `failed`. The same executor that backs the web wizard runs the actual PVE work, so the guest\'s plan, template, IP source, and disks are applied exactly as they would be from the panel.  A plan (`plan_id`) fills and locks `cores`, `memory_mb`, and `disk_gb`; otherwise supply them explicitly (defaults 1 core, 512 MB, 8 GB). `password` is required unless at least one SSH key is present (via `ssh_keys[]` or an `owner_id` with stored keys). QEMU requires `os_template` as `tpl:<id>` from `GET /hosts/{hostId}/os-templates`. LXC requires exactly one template source, either `lxc_template_id` (from the `managed` list) or `os_template` as a raw volid (from the `available` list). `ip_source` is `dhcp` (default) or `zone:<id>` (from `GET /hosts/{hostId}/ip-zones`) to allocate a static IP. `extra_storage[]`, `extra_size[]`, and `extra_mount[]` are parallel arrays describing additional disks; LXC mounts must be absolute paths and default to `/mnt/disk<N>` when blank. 
     * Create a guest (async)
     */
    async createGuestRaw(requestParameters: CreateGuestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateGuest200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling createGuest().'
            );
        }

        if (requestParameters['guestCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'guestCreateRequest',
                'Required parameter "guestCreateRequest" was null or undefined when calling createGuest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GuestCreateRequestToJSON(requestParameters['guestCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateGuest200ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a QEMU VM or an LXC container. Creation is asynchronous: this call validates the request, enqueues a provisioning job, and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{hostId}/jobs/{jobId}` until `data.status` is `done` or `failed`. The same executor that backs the web wizard runs the actual PVE work, so the guest\'s plan, template, IP source, and disks are applied exactly as they would be from the panel.  A plan (`plan_id`) fills and locks `cores`, `memory_mb`, and `disk_gb`; otherwise supply them explicitly (defaults 1 core, 512 MB, 8 GB). `password` is required unless at least one SSH key is present (via `ssh_keys[]` or an `owner_id` with stored keys). QEMU requires `os_template` as `tpl:<id>` from `GET /hosts/{hostId}/os-templates`. LXC requires exactly one template source, either `lxc_template_id` (from the `managed` list) or `os_template` as a raw volid (from the `available` list). `ip_source` is `dhcp` (default) or `zone:<id>` (from `GET /hosts/{hostId}/ip-zones`) to allocate a static IP. `extra_storage[]`, `extra_size[]`, and `extra_mount[]` are parallel arrays describing additional disks; LXC mounts must be absolute paths and default to `/mnt/disk<N>` when blank. 
     * Create a guest (async)
     */
    async createGuest(requestParameters: CreateGuestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateGuest200Response> {
        const response = await this.createGuestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a snapshot. QEMU guests may include RAM state via `vmstate`.
     * Create a snapshot
     */
    async createSnapshotRaw(requestParameters: CreateSnapshotOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling createSnapshot().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling createSnapshot().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling createSnapshot().'
            );
        }

        if (requestParameters['createSnapshotRequest'] == null) {
            throw new runtime.RequiredError(
                'createSnapshotRequest',
                'Required parameter "createSnapshotRequest" was null or undefined when calling createSnapshot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/snapshots`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSnapshotRequestToJSON(requestParameters['createSnapshotRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Creates a snapshot. QEMU guests may include RAM state via `vmstate`.
     * Create a snapshot
     */
    async createSnapshot(requestParameters: CreateSnapshotOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.createSnapshotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes the guest. `node` is required as a query parameter.
     * Delete a guest
     */
    async deleteGuestRaw(requestParameters: DeleteGuestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling deleteGuest().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling deleteGuest().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling deleteGuest().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling deleteGuest().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Deletes the guest. `node` is required as a query parameter.
     * Delete a guest
     */
    async deleteGuest(requestParameters: DeleteGuestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.deleteGuestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a snapshot
     */
    async deleteSnapshotRaw(requestParameters: DeleteSnapshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling deleteSnapshot().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling deleteSnapshot().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling deleteSnapshot().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteSnapshot().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/snapshots/{name}`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Delete a snapshot
     */
    async deleteSnapshot(requestParameters: DeleteSnapshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.deleteSnapshotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Guest detail from the latest inventory snapshot (DB-backed, no live PVE call).
     * Get guest detail
     */
    async getGuestRaw(requestParameters: GetGuestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetGuest200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling getGuest().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling getGuest().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling getGuest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetGuest200ResponseFromJSON(jsonValue));
    }

    /**
     * Guest detail from the latest inventory snapshot (DB-backed, no live PVE call).
     * Get guest detail
     */
    async getGuest(requestParameters: GetGuestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetGuest200Response> {
        const response = await this.getGuestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Whether the per-guest anti-spoof IP filter is on, plus its allow-list and the guest\'s assigned CIDRs.
     * Anti-spoof IP filter status
     */
    async getGuestIpFilterRaw(requestParameters: GetGuestIpFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling getGuestIpFilter().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling getGuestIpFilter().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling getGuestIpFilter().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/ipfilter`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Whether the per-guest anti-spoof IP filter is on, plus its allow-list and the guest\'s assigned CIDRs.
     * Anti-spoof IP filter status
     */
    async getGuestIpFilter(requestParameters: GetGuestIpFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.getGuestIpFilterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Chart-ready time series built from the DB-backed guest metrics table, not a live PVE call. Points are `[epoch_ms, value]` pairs. 
     * Guest CPU/mem/disk/net time series
     */
    async getGuestUsageRaw(requestParameters: GetGuestUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetNodeUsage200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling getGuestUsage().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling getGuestUsage().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling getGuestUsage().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getGuestUsage().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        if (requestParameters['range'] != null) {
            queryParameters['range'] = requestParameters['range'];
        }

        if (requestParameters['metrics'] != null) {
            queryParameters['metrics'] = requestParameters['metrics'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/usage`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetNodeUsage200ResponseFromJSON(jsonValue));
    }

    /**
     * Chart-ready time series built from the DB-backed guest metrics table, not a live PVE call. Points are `[epoch_ms, value]` pairs. 
     * Guest CPU/mem/disk/net time series
     */
    async getGuestUsage(requestParameters: GetGuestUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetNodeUsage200Response> {
        const response = await this.getGuestUsageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The DB-backed per-guest activity log, newest first. Paginated.
     * Guest activity log
     */
    async listGuestEventsRaw(requestParameters: ListGuestEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling listGuestEvents().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling listGuestEvents().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling listGuestEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/events`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * The DB-backed per-guest activity log, newest first. Paginated.
     * Guest activity log
     */
    async listGuestEvents(requestParameters: ListGuestEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.listGuestEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Every IP assigned to the guest (its primary plus any customer-pool IPs) and the resulting CIDR set.
     * List the guest\'s assigned IPs
     */
    async listGuestIpsRaw(requestParameters: ListGuestIpsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling listGuestIps().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling listGuestIps().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling listGuestIps().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/ips`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Every IP assigned to the guest (its primary plus any customer-pool IPs) and the resulting CIDR set.
     * List the guest\'s assigned IPs
     */
    async listGuestIps(requestParameters: ListGuestIpsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.listGuestIpsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Guest list from the latest inventory snapshot (DB-backed, no live PVE call), filterable by `node`, `type`, and `status`. Paginated. 
     * List guests
     */
    async listGuestsRaw(requestParameters: ListGuestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListGuests200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling listGuests().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListGuests200ResponseFromJSON(jsonValue));
    }

    /**
     * Guest list from the latest inventory snapshot (DB-backed, no live PVE call), filterable by `node`, `type`, and `status`. Paginated. 
     * List guests
     */
    async listGuests(requestParameters: ListGuestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListGuests200Response> {
        const response = await this.listGuestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Live PVE read of a guest\'s snapshots, newest first.
     * List guest snapshots
     */
    async listSnapshotsRaw(requestParameters: ListSnapshotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling listSnapshots().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling listSnapshots().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling listSnapshots().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/snapshots`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Live PVE read of a guest\'s snapshots, newest first.
     * List guest snapshots
     */
    async listSnapshots(requestParameters: ListSnapshotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.listSnapshotsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Starts, stops, shuts down, reboots, suspends, or resumes the guest.
     * Power action
     */
    async powerGuestRaw(requestParameters: PowerGuestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling powerGuest().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling powerGuest().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling powerGuest().'
            );
        }

        if (requestParameters['powerGuestRequest'] == null) {
            throw new runtime.RequiredError(
                'powerGuestRequest',
                'Required parameter "powerGuestRequest" was null or undefined when calling powerGuest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/power`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PowerGuestRequestToJSON(requestParameters['powerGuestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Starts, stops, shuts down, reboots, suspends, or resumes the guest.
     * Power action
     */
    async powerGuest(requestParameters: PowerGuestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.powerGuestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes and recreates the guest, keeping its vmid and specs, with a fresh OS. For QEMU, `os_template` must be `tpl:<id>` from `GET /hosts/{hostId}/os-templates`. For LXC, `os_template` is a raw `vztmpl` volid. `password` is required unless at least one SSH key is present via `ssh_keys[]`. Asynchronous, same job/poll pattern as create. 
     * Reinstall a guest (async)
     */
    async reinstallGuestRaw(requestParameters: ReinstallGuestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateGuest200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling reinstallGuest().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling reinstallGuest().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling reinstallGuest().'
            );
        }

        if (requestParameters['reinstallGuestRequest'] == null) {
            throw new runtime.RequiredError(
                'reinstallGuestRequest',
                'Required parameter "reinstallGuestRequest" was null or undefined when calling reinstallGuest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/reinstall`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReinstallGuestRequestToJSON(requestParameters['reinstallGuestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateGuest200ResponseFromJSON(jsonValue));
    }

    /**
     * Deletes and recreates the guest, keeping its vmid and specs, with a fresh OS. For QEMU, `os_template` must be `tpl:<id>` from `GET /hosts/{hostId}/os-templates`. For LXC, `os_template` is a raw `vztmpl` volid. `password` is required unless at least one SSH key is present via `ssh_keys[]`. Asynchronous, same job/poll pattern as create. 
     * Reinstall a guest (async)
     */
    async reinstallGuest(requestParameters: ReinstallGuestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateGuest200Response> {
        const response = await this.reinstallGuestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change CPU cores and/or memory (MB), and/or grow a disk. Provide any of `cores`, `memory_mb`, or `disk` + `size`. Cores/memory apply on the next reboot; disk grow is immediate and grow-only (shrinking is rejected). 
     * Resize cores, memory, and/or a disk
     */
    async resizeGuestRaw(requestParameters: ResizeGuestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling resizeGuest().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling resizeGuest().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling resizeGuest().'
            );
        }

        if (requestParameters['resizeGuestRequest'] == null) {
            throw new runtime.RequiredError(
                'resizeGuestRequest',
                'Required parameter "resizeGuestRequest" was null or undefined when calling resizeGuest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/resize`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResizeGuestRequestToJSON(requestParameters['resizeGuestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Change CPU cores and/or memory (MB), and/or grow a disk. Provide any of `cores`, `memory_mb`, or `disk` + `size`. Cores/memory apply on the next reboot; disk grow is immediate and grow-only (shrinking is rejected). 
     * Resize cores, memory, and/or a disk
     */
    async resizeGuest(requestParameters: ResizeGuestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.resizeGuestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reverts the guest to a snapshot. Stop the guest first unless the snapshot has a saved RAM state.
     * Roll back to a snapshot
     */
    async rollbackSnapshotRaw(requestParameters: RollbackSnapshotOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling rollbackSnapshot().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling rollbackSnapshot().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling rollbackSnapshot().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling rollbackSnapshot().'
            );
        }

        if (requestParameters['rollbackSnapshotRequest'] == null) {
            throw new runtime.RequiredError(
                'rollbackSnapshotRequest',
                'Required parameter "rollbackSnapshotRequest" was null or undefined when calling rollbackSnapshot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/snapshots/{name}/rollback`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RollbackSnapshotRequestToJSON(requestParameters['rollbackSnapshotRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Reverts the guest to a snapshot. Stop the guest first unless the snapshot has a saved RAM state.
     * Roll back to a snapshot
     */
    async rollbackSnapshot(requestParameters: RollbackSnapshotOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.rollbackSnapshotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Enabling requires the guest to already hold an assigned IP; the allow-list is the union of every IP assigned to the guest.
     * Toggle the anti-spoof IP filter
     */
    async setGuestIpFilterRaw(requestParameters: SetGuestIpFilterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling setGuestIpFilter().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling setGuestIpFilter().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling setGuestIpFilter().'
            );
        }

        if (requestParameters['setGuestIpFilterRequest'] == null) {
            throw new runtime.RequiredError(
                'setGuestIpFilterRequest',
                'Required parameter "setGuestIpFilterRequest" was null or undefined when calling setGuestIpFilter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/ipfilter`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetGuestIpFilterRequestToJSON(requestParameters['setGuestIpFilterRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Enabling requires the guest to already hold an assigned IP; the allow-list is the union of every IP assigned to the guest.
     * Toggle the anti-spoof IP filter
     */
    async setGuestIpFilter(requestParameters: SetGuestIpFilterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.setGuestIpFilterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sets a static or DHCP `ipconfig` on the guest\'s primary NIC. Reboot the guest to apply the change. 
     * Set the guest\'s network configuration
     */
    async setGuestIpconfigRaw(requestParameters: SetGuestIpconfigOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling setGuestIpconfig().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling setGuestIpconfig().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling setGuestIpconfig().'
            );
        }

        if (requestParameters['setGuestIpconfigRequest'] == null) {
            throw new runtime.RequiredError(
                'setGuestIpconfigRequest',
                'Required parameter "setGuestIpconfigRequest" was null or undefined when calling setGuestIpconfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/ipconfig`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetGuestIpconfigRequestToJSON(requestParameters['setGuestIpconfigRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Sets a static or DHCP `ipconfig` on the guest\'s primary NIC. Reboot the guest to apply the change. 
     * Set the guest\'s network configuration
     */
    async setGuestIpconfig(requestParameters: SetGuestIpconfigOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.setGuestIpconfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sets a new password for the guest\'s login user, minimum 5 characters. By default (async provisioning enabled) the work is queued and the response is `{queued, job_id}` — poll GET /hosts/{hostId}/jobs/{jobId} for the outcome. When async provisioning is off the change runs synchronously and the response is `{changed: true}`. 
     * Reset the guest\'s root password
     */
    async setGuestPasswordRaw(requestParameters: SetGuestPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SetGuestPassword200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling setGuestPassword().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling setGuestPassword().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling setGuestPassword().'
            );
        }

        if (requestParameters['setGuestPasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'setGuestPasswordRequest',
                'Required parameter "setGuestPasswordRequest" was null or undefined when calling setGuestPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/password`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetGuestPasswordRequestToJSON(requestParameters['setGuestPasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SetGuestPassword200ResponseFromJSON(jsonValue));
    }

    /**
     * Sets a new password for the guest\'s login user, minimum 5 characters. By default (async provisioning enabled) the work is queued and the response is `{queued, job_id}` — poll GET /hosts/{hostId}/jobs/{jobId} for the outcome. When async provisioning is off the change runs synchronously and the response is `{changed: true}`. 
     * Reset the guest\'s root password
     */
    async setGuestPassword(requestParameters: SetGuestPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SetGuestPassword200Response> {
        const response = await this.setGuestPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unassign an IP from the guest
     */
    async unassignGuestIpRaw(requestParameters: UnassignGuestIpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling unassignGuestIp().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling unassignGuestIp().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling unassignGuestIp().'
            );
        }

        if (requestParameters['ipId'] == null) {
            throw new runtime.RequiredError(
                'ipId',
                'Required parameter "ipId" was null or undefined when calling unassignGuestIp().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ipId'] != null) {
            queryParameters['ip_id'] = requestParameters['ipId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/guests/{type}/{vmid}/ips`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Unassign an IP from the guest
     */
    async unassignGuestIp(requestParameters: UnassignGuestIpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.unassignGuestIpRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AssignGuestIpOperationTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type AssignGuestIpOperationTypeEnum = typeof AssignGuestIpOperationTypeEnum[keyof typeof AssignGuestIpOperationTypeEnum];
/**
 * @export
 */
export const CreateSnapshotOperationTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type CreateSnapshotOperationTypeEnum = typeof CreateSnapshotOperationTypeEnum[keyof typeof CreateSnapshotOperationTypeEnum];
/**
 * @export
 */
export const DeleteGuestTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type DeleteGuestTypeEnum = typeof DeleteGuestTypeEnum[keyof typeof DeleteGuestTypeEnum];
/**
 * @export
 */
export const DeleteSnapshotTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type DeleteSnapshotTypeEnum = typeof DeleteSnapshotTypeEnum[keyof typeof DeleteSnapshotTypeEnum];
/**
 * @export
 */
export const GetGuestTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type GetGuestTypeEnum = typeof GetGuestTypeEnum[keyof typeof GetGuestTypeEnum];
/**
 * @export
 */
export const GetGuestIpFilterTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type GetGuestIpFilterTypeEnum = typeof GetGuestIpFilterTypeEnum[keyof typeof GetGuestIpFilterTypeEnum];
/**
 * @export
 */
export const GetGuestUsageTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type GetGuestUsageTypeEnum = typeof GetGuestUsageTypeEnum[keyof typeof GetGuestUsageTypeEnum];
/**
 * @export
 */
export const GetGuestUsageRangeEnum = {
    _30m: '30m',
    _3h: '3h',
    _24h: '24h'
} as const;
export type GetGuestUsageRangeEnum = typeof GetGuestUsageRangeEnum[keyof typeof GetGuestUsageRangeEnum];
/**
 * @export
 */
export const ListGuestEventsTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type ListGuestEventsTypeEnum = typeof ListGuestEventsTypeEnum[keyof typeof ListGuestEventsTypeEnum];
/**
 * @export
 */
export const ListGuestIpsTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type ListGuestIpsTypeEnum = typeof ListGuestIpsTypeEnum[keyof typeof ListGuestIpsTypeEnum];
/**
 * @export
 */
export const ListGuestsTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type ListGuestsTypeEnum = typeof ListGuestsTypeEnum[keyof typeof ListGuestsTypeEnum];
/**
 * @export
 */
export const ListSnapshotsTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type ListSnapshotsTypeEnum = typeof ListSnapshotsTypeEnum[keyof typeof ListSnapshotsTypeEnum];
/**
 * @export
 */
export const PowerGuestOperationTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type PowerGuestOperationTypeEnum = typeof PowerGuestOperationTypeEnum[keyof typeof PowerGuestOperationTypeEnum];
/**
 * @export
 */
export const ReinstallGuestOperationTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type ReinstallGuestOperationTypeEnum = typeof ReinstallGuestOperationTypeEnum[keyof typeof ReinstallGuestOperationTypeEnum];
/**
 * @export
 */
export const ResizeGuestOperationTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type ResizeGuestOperationTypeEnum = typeof ResizeGuestOperationTypeEnum[keyof typeof ResizeGuestOperationTypeEnum];
/**
 * @export
 */
export const RollbackSnapshotOperationTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type RollbackSnapshotOperationTypeEnum = typeof RollbackSnapshotOperationTypeEnum[keyof typeof RollbackSnapshotOperationTypeEnum];
/**
 * @export
 */
export const SetGuestIpFilterOperationTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type SetGuestIpFilterOperationTypeEnum = typeof SetGuestIpFilterOperationTypeEnum[keyof typeof SetGuestIpFilterOperationTypeEnum];
/**
 * @export
 */
export const SetGuestIpconfigOperationTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type SetGuestIpconfigOperationTypeEnum = typeof SetGuestIpconfigOperationTypeEnum[keyof typeof SetGuestIpconfigOperationTypeEnum];
/**
 * @export
 */
export const SetGuestPasswordOperationTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type SetGuestPasswordOperationTypeEnum = typeof SetGuestPasswordOperationTypeEnum[keyof typeof SetGuestPasswordOperationTypeEnum];
/**
 * @export
 */
export const UnassignGuestIpTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type UnassignGuestIpTypeEnum = typeof UnassignGuestIpTypeEnum[keyof typeof UnassignGuestIpTypeEnum];
