/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateHostRequest,
  Envelope,
  GetNode200Response,
  GetNodeUsage200Response,
  GetUsageSummary200Response,
  ListHosts200Response,
  ListNodes200Response,
  UpdateHostRequest,
} from '../models/index';
import {
    CreateHostRequestFromJSON,
    CreateHostRequestToJSON,
    EnvelopeFromJSON,
    EnvelopeToJSON,
    GetNode200ResponseFromJSON,
    GetNode200ResponseToJSON,
    GetNodeUsage200ResponseFromJSON,
    GetNodeUsage200ResponseToJSON,
    GetUsageSummary200ResponseFromJSON,
    GetUsageSummary200ResponseToJSON,
    ListHosts200ResponseFromJSON,
    ListHosts200ResponseToJSON,
    ListNodes200ResponseFromJSON,
    ListNodes200ResponseToJSON,
    UpdateHostRequestFromJSON,
    UpdateHostRequestToJSON,
} from '../models/index';

export interface CreateHostOperationRequest {
    createHostRequest: CreateHostRequest;
}

export interface DeleteHostRequest {
    hostId: number;
}

export interface GetNodeRequest {
    hostId: number;
    node: string;
}

export interface GetNodeUsageRequest {
    hostId: number;
    node: string;
    range?: GetNodeUsageRangeEnum;
    metrics?: string;
}

export interface GetUsageSummaryRequest {
    hostId: number;
}

export interface ListNodesRequest {
    hostId: number;
}

export interface ProvisionImageStorageRequest {
    hostId: number;
}

export interface UpdateHostOperationRequest {
    hostId: number;
    updateHostRequest: UpdateHostRequest;
}

/**
 * 
 */
export class HostsNodesApi extends runtime.BaseAPI {

    /**
     * Creates an encrypted host row; SSH agent onboarding stays a panel action. Never returns secrets.
     * Create a host
     */
    async createHostRaw(requestParameters: CreateHostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['createHostRequest'] == null) {
            throw new runtime.RequiredError(
                'createHostRequest',
                'Required parameter "createHostRequest" was null or undefined when calling createHost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateHostRequestToJSON(requestParameters['createHostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Creates an encrypted host row; SSH agent onboarding stays a panel action. Never returns secrets.
     * Create a host
     */
    async createHost(requestParameters: CreateHostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.createHostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Full DB purge of the host and all its per-host data. The on-host agent/storage wipe stays a panel action.
     * Delete a host
     */
    async deleteHostRaw(requestParameters: DeleteHostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling deleteHost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Full DB purge of the host and all its per-host data. The on-host agent/storage wipe stays a panel action.
     * Delete a host
     */
    async deleteHost(requestParameters: DeleteHostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.deleteHostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Live PVE node status for a single node (CPU info, memory, root filesystem, load average, PVE version, and so on). The response passes through Proxmox\'s own node status object. 
     * Get live node detail
     */
    async getNodeRaw(requestParameters: GetNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetNode200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling getNode().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getNode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/nodes/{node}`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"node"}}`, encodeURIComponent(String(requestParameters['node'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetNode200ResponseFromJSON(jsonValue));
    }

    /**
     * Live PVE node status for a single node (CPU info, memory, root filesystem, load average, PVE version, and so on). The response passes through Proxmox\'s own node status object. 
     * Get live node detail
     */
    async getNode(requestParameters: GetNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetNode200Response> {
        const response = await this.getNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Chart-ready time series built from the DB-backed node metrics table, not a live PVE call. Points are `[epoch_ms, value]` pairs. 
     * Node CPU/mem/disk/net time series
     */
    async getNodeUsageRaw(requestParameters: GetNodeUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetNodeUsage200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling getNodeUsage().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getNodeUsage().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['range'] != null) {
            queryParameters['range'] = requestParameters['range'];
        }

        if (requestParameters['metrics'] != null) {
            queryParameters['metrics'] = requestParameters['metrics'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/nodes/{node}/usage`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"node"}}`, encodeURIComponent(String(requestParameters['node'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetNodeUsage200ResponseFromJSON(jsonValue));
    }

    /**
     * Chart-ready time series built from the DB-backed node metrics table, not a live PVE call. Points are `[epoch_ms, value]` pairs. 
     * Node CPU/mem/disk/net time series
     */
    async getNodeUsage(requestParameters: GetNodeUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetNodeUsage200Response> {
        const response = await this.getNodeUsageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Guests up/down/total and summed cores/memory/disk across the host\'s latest inventory snapshot, DB-backed, no live PVE call. 
     * Host usage summary
     */
    async getUsageSummaryRaw(requestParameters: GetUsageSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUsageSummary200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling getUsageSummary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/usage/summary`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUsageSummary200ResponseFromJSON(jsonValue));
    }

    /**
     * Guests up/down/total and summed cores/memory/disk across the host\'s latest inventory snapshot, DB-backed, no live PVE call. 
     * Host usage summary
     */
    async getUsageSummary(requestParameters: GetUsageSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUsageSummary200Response> {
        const response = await this.getUsageSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the panel\'s configured PVE hosts, scoped to the calling token\'s host_scope (an unscoped token sees all hosts). Never includes credentials. 
     * List configured hosts
     */
    async listHostsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListHosts200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListHosts200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the panel\'s configured PVE hosts, scoped to the calling token\'s host_scope (an unscoped token sees all hosts). Never includes credentials. 
     * List configured hosts
     */
    async listHosts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListHosts200Response> {
        const response = await this.listHostsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Live PVE node list for the given host (real-time call to Proxmox).
     * List a host\'s live nodes
     */
    async listNodesRaw(requestParameters: ListNodesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListNodes200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling listNodes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/nodes`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListNodes200ResponseFromJSON(jsonValue));
    }

    /**
     * Live PVE node list for the given host (real-time call to Proxmox).
     * List a host\'s live nodes
     */
    async listNodes(requestParameters: ListNodesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListNodes200Response> {
        const response = await this.listNodesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Enqueues the agent job that ensures the managed nexovirt-images storage on the node. Requires an active agent.
     * Provision the nexovirt-images storage
     */
    async provisionImageStorageRaw(requestParameters: ProvisionImageStorageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling provisionImageStorage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/provision-image-storage`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Enqueues the agent job that ensures the managed nexovirt-images storage on the node. Requires an active agent.
     * Provision the nexovirt-images storage
     */
    async provisionImageStorage(requestParameters: ProvisionImageStorageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.provisionImageStorageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * An empty or absent password leaves the stored one unchanged.
     * Update a host
     */
    async updateHostRaw(requestParameters: UpdateHostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling updateHost().'
            );
        }

        if (requestParameters['updateHostRequest'] == null) {
            throw new runtime.RequiredError(
                'updateHostRequest',
                'Required parameter "updateHostRequest" was null or undefined when calling updateHost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateHostRequestToJSON(requestParameters['updateHostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * An empty or absent password leaves the stored one unchanged.
     * Update a host
     */
    async updateHost(requestParameters: UpdateHostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.updateHostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetNodeUsageRangeEnum = {
    _30m: '30m',
    _3h: '3h',
    _24h: '24h'
} as const;
export type GetNodeUsageRangeEnum = typeof GetNodeUsageRangeEnum[keyof typeof GetNodeUsageRangeEnum];
