/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Envelope,
  ListNetworks200Response,
  ListStorages200Response,
} from '../models/index';
import {
    EnvelopeFromJSON,
    EnvelopeToJSON,
    ListNetworks200ResponseFromJSON,
    ListNetworks200ResponseToJSON,
    ListStorages200ResponseFromJSON,
    ListStorages200ResponseToJSON,
} from '../models/index';

export interface ListNetworksRequest {
    hostId: number;
    node?: string;
    page?: number;
    perPage?: number;
}

export interface ListStoragesRequest {
    hostId: number;
    node?: string;
    page?: number;
    perPage?: number;
}

/**
 * 
 */
export class InventoryApi extends runtime.BaseAPI {

    /**
     * Node network interfaces from the latest inventory snapshot (DB-backed, no live PVE read), enriched with bridge classification. `role` is one of `WAN`, `Private`, `Internal`, or `Other`. Paginated. 
     * List network interfaces
     */
    async listNetworksRaw(requestParameters: ListNetworksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListNetworks200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling listNetworks().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/networks`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListNetworks200ResponseFromJSON(jsonValue));
    }

    /**
     * Node network interfaces from the latest inventory snapshot (DB-backed, no live PVE read), enriched with bridge classification. `role` is one of `WAN`, `Private`, `Internal`, or `Other`. Paginated. 
     * List network interfaces
     */
    async listNetworks(requestParameters: ListNetworksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListNetworks200Response> {
        const response = await this.listNetworksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Node storages from the latest inventory snapshot (DB-backed, no live PVE read). With `?node=`, returns that node\'s storages plus any datacenter-wide/shared entries (a row with an empty node, for example shared NFS or PBS storage, matches every node). Paginated. Filter by `content` client-side, for example `images` for VM disks or `rootdir` for LXC. 
     * List storages
     */
    async listStoragesRaw(requestParameters: ListStoragesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListStorages200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling listStorages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/storages`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListStorages200ResponseFromJSON(jsonValue));
    }

    /**
     * Node storages from the latest inventory snapshot (DB-backed, no live PVE read). With `?node=`, returns that node\'s storages plus any datacenter-wide/shared entries (a row with an empty node, for example shared NFS or PBS storage, matches every node). Paginated. Filter by `content` client-side, for example `images` for VM disks or `rootdir` for LXC. 
     * List storages
     */
    async listStorages(requestParameters: ListStoragesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListStorages200Response> {
        const response = await this.listStoragesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
