/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Envelope,
  GetProvisioningJob200Response,
} from '../models/index';
import {
    EnvelopeFromJSON,
    EnvelopeToJSON,
    GetProvisioningJob200ResponseFromJSON,
    GetProvisioningJob200ResponseToJSON,
} from '../models/index';

export interface GetProvisioningJobRequest {
    hostId: number;
    jobId: number;
}

export interface GetPveTaskRequest {
    hostId: number;
    node: string;
    upid: string;
}

/**
 * 
 */
export class JobsTasksApi extends runtime.BaseAPI {

    /**
     * Poll this to track a create, reinstall, delete, or power job enqueued when `provision.async` is enabled. `status` transitions `queued` to `running` to a terminal state, either `done` or `failed`. On failure, `error` carries the reason. 
     * Get an async provisioning job\'s status
     */
    async getProvisioningJobRaw(requestParameters: GetProvisioningJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetProvisioningJob200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling getProvisioningJob().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getProvisioningJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/jobs/{jobId}`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetProvisioningJob200ResponseFromJSON(jsonValue));
    }

    /**
     * Poll this to track a create, reinstall, delete, or power job enqueued when `provision.async` is enabled. `status` transitions `queued` to `running` to a terminal state, either `done` or `failed`. On failure, `error` carries the reason. 
     * Get an async provisioning job\'s status
     */
    async getProvisioningJob(requestParameters: GetProvisioningJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetProvisioningJob200Response> {
        const response = await this.getProvisioningJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * A live PVE task status lookup by UPID, for tracking the underlying Proxmox task directly (as opposed to the panel\'s own provisioning job). 
     * Get a live PVE task\'s status
     */
    async getPveTaskRaw(requestParameters: GetPveTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling getPveTask().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getPveTask().'
            );
        }

        if (requestParameters['upid'] == null) {
            throw new runtime.RequiredError(
                'upid',
                'Required parameter "upid" was null or undefined when calling getPveTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/tasks/{node}/{upid}`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"node"}}`, encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace(`{${"upid"}}`, encodeURIComponent(String(requestParameters['upid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * A live PVE task status lookup by UPID, for tracking the underlying Proxmox task directly (as opposed to the panel\'s own provisioning job). 
     * Get a live PVE task\'s status
     */
    async getPveTask(requestParameters: GetPveTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.getPveTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
