/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Envelope,
  GetNextVmid200Response,
  ListCtTemplates200Response,
  ListIpZones200Response,
  ListOsTemplates200Response,
  ListPlans200Response,
  ListUserSshKeys200Response,
} from '../models/index';
import {
    EnvelopeFromJSON,
    EnvelopeToJSON,
    GetNextVmid200ResponseFromJSON,
    GetNextVmid200ResponseToJSON,
    ListCtTemplates200ResponseFromJSON,
    ListCtTemplates200ResponseToJSON,
    ListIpZones200ResponseFromJSON,
    ListIpZones200ResponseToJSON,
    ListOsTemplates200ResponseFromJSON,
    ListOsTemplates200ResponseToJSON,
    ListPlans200ResponseFromJSON,
    ListPlans200ResponseToJSON,
    ListUserSshKeys200ResponseFromJSON,
    ListUserSshKeys200ResponseToJSON,
} from '../models/index';

export interface GetNextVmidRequest {
    hostId: number;
}

export interface ListCtTemplatesRequest {
    hostId: number;
    node?: string;
}

export interface ListIpZonesRequest {
    hostId: number;
    page?: number;
    perPage?: number;
}

export interface ListOsTemplatesRequest {
    hostId: number;
    page?: number;
    perPage?: number;
}

export interface ListPlansRequest {
    hostId: number;
    page?: number;
    perPage?: number;
}

export interface ListUserSshKeysRequest {
    userId: number;
}

/**
 * 
 */
export class ProvisioningDiscoveryApi extends runtime.BaseAPI {

    /**
     * A free VMID from the live PVE `cluster/nextid` call. Create still requires an explicit `vmid` in the body; use this to obtain one. 
     * Get the next free VMID
     */
    async getNextVmidRaw(requestParameters: GetNextVmidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetNextVmid200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling getNextVmid().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/next-vmid`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetNextVmid200ResponseFromJSON(jsonValue));
    }

    /**
     * A free VMID from the live PVE `cluster/nextid` call. Create still requires an explicit `vmid` in the body; use this to obtain one. 
     * Get the next free VMID
     */
    async getNextVmid(requestParameters: GetNextVmidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetNextVmid200Response> {
        const response = await this.getNextVmidRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * LXC template options. `managed` is the panel\'s own CT template library (`lxc_template_id` is the create argument, staged on demand). `available` is live PVE `vztmpl` volumes on `?node` (only populated when a valid `node` is given; `volid` is the create argument). Without `?node`, `available` is an empty array and no PVE call is made. Not paginated. 
     * List LXC container templates
     */
    async listCtTemplatesRaw(requestParameters: ListCtTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCtTemplates200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling listCtTemplates().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/ct-templates`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListCtTemplates200ResponseFromJSON(jsonValue));
    }

    /**
     * LXC template options. `managed` is the panel\'s own CT template library (`lxc_template_id` is the create argument, staged on demand). `available` is live PVE `vztmpl` volumes on `?node` (only populated when a valid `node` is given; `volid` is the create argument). Without `?node`, `available` is an empty array and no PVE call is made. Not paginated. 
     * List LXC container templates
     */
    async listCtTemplates(requestParameters: ListCtTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCtTemplates200Response> {
        const response = await this.listCtTemplatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The host\'s IP zones (IPAM). `ref` (for example `zone:3`) is the exact `ip_source` create value; using it allocates a static IP from the zone\'s pool. Paginated. 
     * List IP zones
     */
    async listIpZonesRaw(requestParameters: ListIpZonesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListIpZones200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling listIpZones().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/ip-zones`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListIpZones200ResponseFromJSON(jsonValue));
    }

    /**
     * The host\'s IP zones (IPAM). `ref` (for example `zone:3`) is the exact `ip_source` create value; using it allocates a static IP from the zone\'s pool. Paginated. 
     * List IP zones
     */
    async listIpZones(requestParameters: ListIpZonesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListIpZones200Response> {
        const response = await this.listIpZonesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Cloud-init OS templates for QEMU. `ref` (for example `tpl:7`) is the exact `os_template` value to send at create. Never returns SSH keys or other cloud-init secrets. Paginated. 
     * List QEMU OS templates
     */
    async listOsTemplatesRaw(requestParameters: ListOsTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListOsTemplates200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling listOsTemplates().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/os-templates`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListOsTemplates200ResponseFromJSON(jsonValue));
    }

    /**
     * Cloud-init OS templates for QEMU. `ref` (for example `tpl:7`) is the exact `os_template` value to send at create. Never returns SSH keys or other cloud-init secrets. Paginated. 
     * List QEMU OS templates
     */
    async listOsTemplates(requestParameters: ListOsTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListOsTemplates200Response> {
        const response = await this.listOsTemplatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Active resource plans usable as `plan_id` at create time. A plan fills and locks `cores`, `memory_mb`, and `disk_gb` on the created guest. Paginated. 
     * List resource plans
     */
    async listPlansRaw(requestParameters: ListPlansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPlans200Response>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling listPlans().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hosts/{hostId}/plans`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPlans200ResponseFromJSON(jsonValue));
    }

    /**
     * Active resource plans usable as `plan_id` at create time. A plan fills and locks `cores`, `memory_mb`, and `disk_gb` on the created guest. Paginated. 
     * List resource plans
     */
    async listPlans(requestParameters: ListPlansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPlans200Response> {
        const response = await this.listPlansRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * A user\'s stored SSH keys, exposing only `id`, `name`, and `fingerprint`, never the key body. Pass the owner\'s id as `owner_id` at create to auto-inject all of that user\'s stored keys. Not paginated. 
     * List a user\'s SSH keys
     */
    async listUserSshKeysRaw(requestParameters: ListUserSshKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListUserSshKeys200Response>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listUserSshKeys().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/ssh-keys`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListUserSshKeys200ResponseFromJSON(jsonValue));
    }

    /**
     * A user\'s stored SSH keys, exposing only `id`, `name`, and `fingerprint`, never the key body. Pass the owner\'s id as `owner_id` at create to auto-inject all of that user\'s stored keys. Not paginated. 
     * List a user\'s SSH keys
     */
    async listUserSshKeys(requestParameters: ListUserSshKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListUserSshKeys200Response> {
        const response = await this.listUserSshKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
