/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddUserSshKeyRequest,
  Envelope,
} from '../models/index';
import {
    AddUserSshKeyRequestFromJSON,
    AddUserSshKeyRequestToJSON,
    EnvelopeFromJSON,
    EnvelopeToJSON,
} from '../models/index';

export interface AddResellerCustomerSshKeyRequest {
    customerId: number;
    addUserSshKeyRequest: AddUserSshKeyRequest;
}

export interface DeleteResellerCustomerSshKeyRequest {
    customerId: number;
    keyId: number;
}

export interface ListResellerCustomerSshKeysRequest {
    customerId: number;
}

/**
 * 
 */
export class ResellerSSHKeysApi extends runtime.BaseAPI {

    /**
     * Add an SSH key
     */
    async addResellerCustomerSshKeyRaw(requestParameters: AddResellerCustomerSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling addResellerCustomerSshKey().'
            );
        }

        if (requestParameters['addUserSshKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'addUserSshKeyRequest',
                'Required parameter "addUserSshKeyRequest" was null or undefined when calling addResellerCustomerSshKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/customers/{customerId}/ssh-keys`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddUserSshKeyRequestToJSON(requestParameters['addUserSshKeyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Add an SSH key
     */
    async addResellerCustomerSshKey(requestParameters: AddResellerCustomerSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.addResellerCustomerSshKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an SSH key
     */
    async deleteResellerCustomerSshKeyRaw(requestParameters: DeleteResellerCustomerSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling deleteResellerCustomerSshKey().'
            );
        }

        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling deleteResellerCustomerSshKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/customers/{customerId}/ssh-keys/{keyId}`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));
        urlPath = urlPath.replace(`{${"keyId"}}`, encodeURIComponent(String(requestParameters['keyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Delete an SSH key
     */
    async deleteResellerCustomerSshKey(requestParameters: DeleteResellerCustomerSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.deleteResellerCustomerSshKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * id/name/fingerprint only, never the key body.
     * List a customer\'s SSH keys
     */
    async listResellerCustomerSshKeysRaw(requestParameters: ListResellerCustomerSshKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling listResellerCustomerSshKeys().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/customers/{customerId}/ssh-keys`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * id/name/fingerprint only, never the key body.
     * List a customer\'s SSH keys
     */
    async listResellerCustomerSshKeys(requestParameters: ListResellerCustomerSshKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.listResellerCustomerSshKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
