/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AssignResellerCustomerRequest,
  AssignResellerNodeRequest,
  AssignResellerPlanRequest,
  AssignResellerZoneRequest,
  CreateReseller200Response,
  CreateResellerPlan200Response,
  CreateResellerRequest,
  Envelope,
  ListResellerPlans200Response,
  ListResellers200Response,
  ResellerPlanInput,
  UpdateResellerRequest,
} from '../models/index';
import {
    AssignResellerCustomerRequestFromJSON,
    AssignResellerCustomerRequestToJSON,
    AssignResellerNodeRequestFromJSON,
    AssignResellerNodeRequestToJSON,
    AssignResellerPlanRequestFromJSON,
    AssignResellerPlanRequestToJSON,
    AssignResellerZoneRequestFromJSON,
    AssignResellerZoneRequestToJSON,
    CreateReseller200ResponseFromJSON,
    CreateReseller200ResponseToJSON,
    CreateResellerPlan200ResponseFromJSON,
    CreateResellerPlan200ResponseToJSON,
    CreateResellerRequestFromJSON,
    CreateResellerRequestToJSON,
    EnvelopeFromJSON,
    EnvelopeToJSON,
    ListResellerPlans200ResponseFromJSON,
    ListResellerPlans200ResponseToJSON,
    ListResellers200ResponseFromJSON,
    ListResellers200ResponseToJSON,
    ResellerPlanInputFromJSON,
    ResellerPlanInputToJSON,
    UpdateResellerRequestFromJSON,
    UpdateResellerRequestToJSON,
} from '../models/index';

export interface AssignResellerCustomerOperationRequest {
    resellerId: number;
    assignResellerCustomerRequest: AssignResellerCustomerRequest;
}

export interface AssignResellerNodeOperationRequest {
    resellerId: number;
    assignResellerNodeRequest: AssignResellerNodeRequest;
}

export interface AssignResellerPlanOperationRequest {
    resellerId: number;
    assignResellerPlanRequest: AssignResellerPlanRequest;
}

export interface AssignResellerZoneOperationRequest {
    resellerId: number;
    assignResellerZoneRequest: AssignResellerZoneRequest;
}

export interface CreateResellerOperationRequest {
    createResellerRequest: CreateResellerRequest;
}

export interface CreateResellerPlanRequest {
    resellerPlanInput: ResellerPlanInput;
}

export interface DeleteResellerRequest {
    resellerId: number;
}

export interface DeleteResellerPlanRequest {
    planId: number;
}

export interface GetResellerRequest {
    resellerId: number;
}

export interface ListResellerPlansRequest {
    page?: number;
    perPage?: number;
}

export interface ListResellersRequest {
    page?: number;
    perPage?: number;
}

export interface ResetResellerPasswordRequest {
    resellerId: number;
}

export interface UnassignResellerCustomerRequest {
    resellerId: number;
    assignResellerCustomerRequest: AssignResellerCustomerRequest;
}

export interface UnassignResellerNodeRequest {
    resellerId: number;
    assignResellerNodeRequest: AssignResellerNodeRequest;
}

export interface UnassignResellerPlanRequest {
    resellerId: number;
}

export interface UnassignResellerZoneRequest {
    resellerId: number;
    assignResellerZoneRequest: AssignResellerZoneRequest;
}

export interface UpdateResellerOperationRequest {
    resellerId: number;
    updateResellerRequest: UpdateResellerRequest;
}

export interface UpdateResellerPlanRequest {
    planId: number;
    resellerPlanInput: ResellerPlanInput;
}

/**
 * 
 */
export class ResellersAdminApi extends runtime.BaseAPI {

    /**
     * Quota-gated (`422` past the reseller\'s plan cap). Enterprise-only.
     * Link a customer to a reseller
     */
    async assignResellerCustomerRaw(requestParameters: AssignResellerCustomerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['resellerId'] == null) {
            throw new runtime.RequiredError(
                'resellerId',
                'Required parameter "resellerId" was null or undefined when calling assignResellerCustomer().'
            );
        }

        if (requestParameters['assignResellerCustomerRequest'] == null) {
            throw new runtime.RequiredError(
                'assignResellerCustomerRequest',
                'Required parameter "assignResellerCustomerRequest" was null or undefined when calling assignResellerCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers/{resellerId}/customers`;
        urlPath = urlPath.replace(`{${"resellerId"}}`, encodeURIComponent(String(requestParameters['resellerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssignResellerCustomerRequestToJSON(requestParameters['assignResellerCustomerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Quota-gated (`422` past the reseller\'s plan cap). Enterprise-only.
     * Link a customer to a reseller
     */
    async assignResellerCustomer(requestParameters: AssignResellerCustomerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.assignResellerCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Grants the reseller access to a (host, node) pair for placement and API guest creation.
     * Grant node access
     */
    async assignResellerNodeRaw(requestParameters: AssignResellerNodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['resellerId'] == null) {
            throw new runtime.RequiredError(
                'resellerId',
                'Required parameter "resellerId" was null or undefined when calling assignResellerNode().'
            );
        }

        if (requestParameters['assignResellerNodeRequest'] == null) {
            throw new runtime.RequiredError(
                'assignResellerNodeRequest',
                'Required parameter "assignResellerNodeRequest" was null or undefined when calling assignResellerNode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers/{resellerId}/nodes`;
        urlPath = urlPath.replace(`{${"resellerId"}}`, encodeURIComponent(String(requestParameters['resellerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssignResellerNodeRequestToJSON(requestParameters['assignResellerNodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Grants the reseller access to a (host, node) pair for placement and API guest creation.
     * Grant node access
     */
    async assignResellerNode(requestParameters: AssignResellerNodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.assignResellerNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Assign a reseller quota plan
     */
    async assignResellerPlanRaw(requestParameters: AssignResellerPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['resellerId'] == null) {
            throw new runtime.RequiredError(
                'resellerId',
                'Required parameter "resellerId" was null or undefined when calling assignResellerPlan().'
            );
        }

        if (requestParameters['assignResellerPlanRequest'] == null) {
            throw new runtime.RequiredError(
                'assignResellerPlanRequest',
                'Required parameter "assignResellerPlanRequest" was null or undefined when calling assignResellerPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers/{resellerId}/plan`;
        urlPath = urlPath.replace(`{${"resellerId"}}`, encodeURIComponent(String(requestParameters['resellerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssignResellerPlanRequestToJSON(requestParameters['assignResellerPlanRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Assign a reseller quota plan
     */
    async assignResellerPlan(requestParameters: AssignResellerPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.assignResellerPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Grant IP-zone access
     */
    async assignResellerZoneRaw(requestParameters: AssignResellerZoneOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['resellerId'] == null) {
            throw new runtime.RequiredError(
                'resellerId',
                'Required parameter "resellerId" was null or undefined when calling assignResellerZone().'
            );
        }

        if (requestParameters['assignResellerZoneRequest'] == null) {
            throw new runtime.RequiredError(
                'assignResellerZoneRequest',
                'Required parameter "assignResellerZoneRequest" was null or undefined when calling assignResellerZone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers/{resellerId}/zones`;
        urlPath = urlPath.replace(`{${"resellerId"}}`, encodeURIComponent(String(requestParameters['resellerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssignResellerZoneRequestToJSON(requestParameters['assignResellerZoneRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Grant IP-zone access
     */
    async assignResellerZone(requestParameters: AssignResellerZoneOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.assignResellerZoneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a `role=reseller` account with a generated password, returned once. Enterprise-only.
     * Create a reseller
     */
    async createResellerRaw(requestParameters: CreateResellerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateReseller200Response>> {
        if (requestParameters['createResellerRequest'] == null) {
            throw new runtime.RequiredError(
                'createResellerRequest',
                'Required parameter "createResellerRequest" was null or undefined when calling createReseller().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateResellerRequestToJSON(requestParameters['createResellerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateReseller200ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a `role=reseller` account with a generated password, returned once. Enterprise-only.
     * Create a reseller
     */
    async createReseller(requestParameters: CreateResellerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateReseller200Response> {
        const response = await this.createResellerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * `0` for any `max_*` cap means unlimited.
     * Create a reseller quota plan
     */
    async createResellerPlanRaw(requestParameters: CreateResellerPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResellerPlan200Response>> {
        if (requestParameters['resellerPlanInput'] == null) {
            throw new runtime.RequiredError(
                'resellerPlanInput',
                'Required parameter "resellerPlanInput" was null or undefined when calling createResellerPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reseller-plans`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResellerPlanInputToJSON(requestParameters['resellerPlanInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateResellerPlan200ResponseFromJSON(jsonValue));
    }

    /**
     * `0` for any `max_*` cap means unlimited.
     * Create a reseller quota plan
     */
    async createResellerPlan(requestParameters: CreateResellerPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResellerPlan200Response> {
        const response = await this.createResellerPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refuses (`422`) while the reseller still has customers assigned. Enterprise-only.
     * Delete a reseller
     */
    async deleteResellerRaw(requestParameters: DeleteResellerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['resellerId'] == null) {
            throw new runtime.RequiredError(
                'resellerId',
                'Required parameter "resellerId" was null or undefined when calling deleteReseller().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers/{resellerId}`;
        urlPath = urlPath.replace(`{${"resellerId"}}`, encodeURIComponent(String(requestParameters['resellerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Refuses (`422`) while the reseller still has customers assigned. Enterprise-only.
     * Delete a reseller
     */
    async deleteReseller(requestParameters: DeleteResellerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.deleteResellerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refuses (`422`) while a reseller still references the plan.
     * Delete a reseller quota plan
     */
    async deleteResellerPlanRaw(requestParameters: DeleteResellerPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['planId'] == null) {
            throw new runtime.RequiredError(
                'planId',
                'Required parameter "planId" was null or undefined when calling deleteResellerPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reseller-plans/{planId}`;
        urlPath = urlPath.replace(`{${"planId"}}`, encodeURIComponent(String(requestParameters['planId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Refuses (`422`) while a reseller still references the plan.
     * Delete a reseller quota plan
     */
    async deleteResellerPlan(requestParameters: DeleteResellerPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.deleteResellerPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Detail plus assigned nodes, assigned IP zones, quota plan id, and current usage. Enterprise-only.
     * Get a reseller
     */
    async getResellerRaw(requestParameters: GetResellerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['resellerId'] == null) {
            throw new runtime.RequiredError(
                'resellerId',
                'Required parameter "resellerId" was null or undefined when calling getReseller().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers/{resellerId}`;
        urlPath = urlPath.replace(`{${"resellerId"}}`, encodeURIComponent(String(requestParameters['resellerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Detail plus assigned nodes, assigned IP zones, quota plan id, and current usage. Enterprise-only.
     * Get a reseller
     */
    async getReseller(requestParameters: GetResellerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.getResellerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List reseller quota plans
     */
    async listResellerPlansRaw(requestParameters: ListResellerPlansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResellerPlans200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reseller-plans`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResellerPlans200ResponseFromJSON(jsonValue));
    }

    /**
     * List reseller quota plans
     */
    async listResellerPlans(requestParameters: ListResellerPlansRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResellerPlans200Response> {
        const response = await this.listResellerPlansRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Paginated list of `role=reseller` accounts. Never includes secrets. Enterprise-only.
     * List resellers
     */
    async listResellersRaw(requestParameters: ListResellersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResellers200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResellers200ResponseFromJSON(jsonValue));
    }

    /**
     * Paginated list of `role=reseller` accounts. Never includes secrets. Enterprise-only.
     * List resellers
     */
    async listResellers(requestParameters: ListResellersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResellers200Response> {
        const response = await this.listResellersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generates a new password, returned once. Enterprise-only.
     * Reset a reseller\'s password
     */
    async resetResellerPasswordRaw(requestParameters: ResetResellerPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['resellerId'] == null) {
            throw new runtime.RequiredError(
                'resellerId',
                'Required parameter "resellerId" was null or undefined when calling resetResellerPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers/{resellerId}/reset-password`;
        urlPath = urlPath.replace(`{${"resellerId"}}`, encodeURIComponent(String(requestParameters['resellerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Generates a new password, returned once. Enterprise-only.
     * Reset a reseller\'s password
     */
    async resetResellerPassword(requestParameters: ResetResellerPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.resetResellerPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unlink a customer from a reseller
     */
    async unassignResellerCustomerRaw(requestParameters: UnassignResellerCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['resellerId'] == null) {
            throw new runtime.RequiredError(
                'resellerId',
                'Required parameter "resellerId" was null or undefined when calling unassignResellerCustomer().'
            );
        }

        if (requestParameters['assignResellerCustomerRequest'] == null) {
            throw new runtime.RequiredError(
                'assignResellerCustomerRequest',
                'Required parameter "assignResellerCustomerRequest" was null or undefined when calling unassignResellerCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers/{resellerId}/customers`;
        urlPath = urlPath.replace(`{${"resellerId"}}`, encodeURIComponent(String(requestParameters['resellerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: AssignResellerCustomerRequestToJSON(requestParameters['assignResellerCustomerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Unlink a customer from a reseller
     */
    async unassignResellerCustomer(requestParameters: UnassignResellerCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.unassignResellerCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke node access
     */
    async unassignResellerNodeRaw(requestParameters: UnassignResellerNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['resellerId'] == null) {
            throw new runtime.RequiredError(
                'resellerId',
                'Required parameter "resellerId" was null or undefined when calling unassignResellerNode().'
            );
        }

        if (requestParameters['assignResellerNodeRequest'] == null) {
            throw new runtime.RequiredError(
                'assignResellerNodeRequest',
                'Required parameter "assignResellerNodeRequest" was null or undefined when calling unassignResellerNode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers/{resellerId}/nodes`;
        urlPath = urlPath.replace(`{${"resellerId"}}`, encodeURIComponent(String(requestParameters['resellerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: AssignResellerNodeRequestToJSON(requestParameters['assignResellerNodeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Revoke node access
     */
    async unassignResellerNode(requestParameters: UnassignResellerNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.unassignResellerNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Clear a reseller\'s quota plan
     */
    async unassignResellerPlanRaw(requestParameters: UnassignResellerPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['resellerId'] == null) {
            throw new runtime.RequiredError(
                'resellerId',
                'Required parameter "resellerId" was null or undefined when calling unassignResellerPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers/{resellerId}/plan`;
        urlPath = urlPath.replace(`{${"resellerId"}}`, encodeURIComponent(String(requestParameters['resellerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Clear a reseller\'s quota plan
     */
    async unassignResellerPlan(requestParameters: UnassignResellerPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.unassignResellerPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke IP-zone access
     */
    async unassignResellerZoneRaw(requestParameters: UnassignResellerZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['resellerId'] == null) {
            throw new runtime.RequiredError(
                'resellerId',
                'Required parameter "resellerId" was null or undefined when calling unassignResellerZone().'
            );
        }

        if (requestParameters['assignResellerZoneRequest'] == null) {
            throw new runtime.RequiredError(
                'assignResellerZoneRequest',
                'Required parameter "assignResellerZoneRequest" was null or undefined when calling unassignResellerZone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers/{resellerId}/zones`;
        urlPath = urlPath.replace(`{${"resellerId"}}`, encodeURIComponent(String(requestParameters['resellerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: AssignResellerZoneRequestToJSON(requestParameters['assignResellerZoneRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Revoke IP-zone access
     */
    async unassignResellerZone(requestParameters: UnassignResellerZoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.unassignResellerZoneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates username, email, and active status. Enterprise-only.
     * Update a reseller
     */
    async updateResellerRaw(requestParameters: UpdateResellerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['resellerId'] == null) {
            throw new runtime.RequiredError(
                'resellerId',
                'Required parameter "resellerId" was null or undefined when calling updateReseller().'
            );
        }

        if (requestParameters['updateResellerRequest'] == null) {
            throw new runtime.RequiredError(
                'updateResellerRequest',
                'Required parameter "updateResellerRequest" was null or undefined when calling updateReseller().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/resellers/{resellerId}`;
        urlPath = urlPath.replace(`{${"resellerId"}}`, encodeURIComponent(String(requestParameters['resellerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateResellerRequestToJSON(requestParameters['updateResellerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Updates username, email, and active status. Enterprise-only.
     * Update a reseller
     */
    async updateReseller(requestParameters: UpdateResellerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.updateResellerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a reseller quota plan
     */
    async updateResellerPlanRaw(requestParameters: UpdateResellerPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateResellerPlan200Response>> {
        if (requestParameters['planId'] == null) {
            throw new runtime.RequiredError(
                'planId',
                'Required parameter "planId" was null or undefined when calling updateResellerPlan().'
            );
        }

        if (requestParameters['resellerPlanInput'] == null) {
            throw new runtime.RequiredError(
                'resellerPlanInput',
                'Required parameter "resellerPlanInput" was null or undefined when calling updateResellerPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reseller-plans/{planId}`;
        urlPath = urlPath.replace(`{${"planId"}}`, encodeURIComponent(String(requestParameters['planId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResellerPlanInputToJSON(requestParameters['resellerPlanInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateResellerPlan200ResponseFromJSON(jsonValue));
    }

    /**
     * Update a reseller quota plan
     */
    async updateResellerPlan(requestParameters: UpdateResellerPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateResellerPlan200Response> {
        const response = await this.updateResellerPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
