/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateResellerGuestRequest,
  Envelope,
  PowerResellerGuestRequest,
} from '../models/index';
import {
    CreateResellerGuestRequestFromJSON,
    CreateResellerGuestRequestToJSON,
    EnvelopeFromJSON,
    EnvelopeToJSON,
    PowerResellerGuestRequestFromJSON,
    PowerResellerGuestRequestToJSON,
} from '../models/index';

export interface CreateResellerGuestOperationRequest {
    createResellerGuestRequest: CreateResellerGuestRequest;
}

export interface DeleteResellerGuestRequest {
    hostId: number;
    type: DeleteResellerGuestTypeEnum;
    vmid: number;
    node: string;
}

export interface GetResellerGuestRequest {
    hostId: number;
    type: GetResellerGuestTypeEnum;
    vmid: number;
}

export interface ListResellerGuestsRequest {
    node?: string;
    type?: ListResellerGuestsTypeEnum;
    status?: string;
}

export interface PowerResellerGuestOperationRequest {
    hostId: number;
    type: PowerResellerGuestOperationTypeEnum;
    vmid: number;
    powerResellerGuestRequest: PowerResellerGuestRequest;
}

/**
 * 
 */
export class ResellerGuestsApi extends runtime.BaseAPI {

    /**
     * `owner_id` must be one of the calling reseller\'s own customers (`404` otherwise). `host_id`/`node` must be a (host, node) pair the reseller was granted; `plan_id` and any `ipv4_zone_id`/`ipv6_zone_id` must likewise belong to the reseller. Same shape as the admin `POST /hosts/{hostId}/guests` body, plus `owner_id`, `host_id`, and `node`. 
     * Create a guest for one of my customers
     */
    async createResellerGuestRaw(requestParameters: CreateResellerGuestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['createResellerGuestRequest'] == null) {
            throw new runtime.RequiredError(
                'createResellerGuestRequest',
                'Required parameter "createResellerGuestRequest" was null or undefined when calling createResellerGuest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/guests`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateResellerGuestRequestToJSON(requestParameters['createResellerGuestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * `owner_id` must be one of the calling reseller\'s own customers (`404` otherwise). `host_id`/`node` must be a (host, node) pair the reseller was granted; `plan_id` and any `ipv4_zone_id`/`ipv6_zone_id` must likewise belong to the reseller. Same shape as the admin `POST /hosts/{hostId}/guests` body, plus `owner_id`, `host_id`, and `node`. 
     * Create a guest for one of my customers
     */
    async createResellerGuest(requestParameters: CreateResellerGuestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.createResellerGuestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a guest
     */
    async deleteResellerGuestRaw(requestParameters: DeleteResellerGuestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling deleteResellerGuest().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling deleteResellerGuest().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling deleteResellerGuest().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling deleteResellerGuest().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/guests/{hostId}/{type}/{vmid}`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Delete a guest
     */
    async deleteResellerGuest(requestParameters: DeleteResellerGuestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.deleteResellerGuestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * `404` unless owned by one of the calling reseller\'s own customers.
     * Get a guest
     */
    async getResellerGuestRaw(requestParameters: GetResellerGuestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling getResellerGuest().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling getResellerGuest().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling getResellerGuest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/guests/{hostId}/{type}/{vmid}`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * `404` unless owned by one of the calling reseller\'s own customers.
     * Get a guest
     */
    async getResellerGuest(requestParameters: GetResellerGuestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.getResellerGuestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Guests owned by the calling reseller\'s own customers, across every node the reseller is assigned.
     * List my guests
     */
    async listResellerGuestsRaw(requestParameters: ListResellerGuestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        const queryParameters: any = {};

        if (requestParameters['node'] != null) {
            queryParameters['node'] = requestParameters['node'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/guests`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Guests owned by the calling reseller\'s own customers, across every node the reseller is assigned.
     * List my guests
     */
    async listResellerGuests(requestParameters: ListResellerGuestsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.listResellerGuestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Power action
     */
    async powerResellerGuestRaw(requestParameters: PowerResellerGuestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling powerResellerGuest().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling powerResellerGuest().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling powerResellerGuest().'
            );
        }

        if (requestParameters['powerResellerGuestRequest'] == null) {
            throw new runtime.RequiredError(
                'powerResellerGuestRequest',
                'Required parameter "powerResellerGuestRequest" was null or undefined when calling powerResellerGuest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/guests/{hostId}/{type}/{vmid}/power`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PowerResellerGuestRequestToJSON(requestParameters['powerResellerGuestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Power action
     */
    async powerResellerGuest(requestParameters: PowerResellerGuestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.powerResellerGuestRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const DeleteResellerGuestTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type DeleteResellerGuestTypeEnum = typeof DeleteResellerGuestTypeEnum[keyof typeof DeleteResellerGuestTypeEnum];
/**
 * @export
 */
export const GetResellerGuestTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type GetResellerGuestTypeEnum = typeof GetResellerGuestTypeEnum[keyof typeof GetResellerGuestTypeEnum];
/**
 * @export
 */
export const ListResellerGuestsTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type ListResellerGuestsTypeEnum = typeof ListResellerGuestsTypeEnum[keyof typeof ListResellerGuestsTypeEnum];
/**
 * @export
 */
export const PowerResellerGuestOperationTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type PowerResellerGuestOperationTypeEnum = typeof PowerResellerGuestOperationTypeEnum[keyof typeof PowerResellerGuestOperationTypeEnum];
