/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChangeResellerGuestIpRequest,
  Envelope,
} from '../models/index';
import {
    ChangeResellerGuestIpRequestFromJSON,
    ChangeResellerGuestIpRequestToJSON,
    EnvelopeFromJSON,
    EnvelopeToJSON,
} from '../models/index';

export interface ChangeResellerGuestIpOperationRequest {
    hostId: number;
    type: ChangeResellerGuestIpOperationTypeEnum;
    vmid: number;
    changeResellerGuestIpRequest: ChangeResellerGuestIpRequest;
}

/**
 * 
 */
export class ResellerNetworkingApi extends runtime.BaseAPI {

    /**
     * `action=change` requires `ip` (must fall inside the target zone\'s range) and assigns it; `action=release` frees the guest\'s current IP for that family. The target zone (`zone_id`, or the guest\'s current single-stack zone if omitted) must be one the calling reseller was granted. Reboot the guest to apply. 
     * Change or release a guest\'s static IP
     */
    async changeResellerGuestIpRaw(requestParameters: ChangeResellerGuestIpOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['hostId'] == null) {
            throw new runtime.RequiredError(
                'hostId',
                'Required parameter "hostId" was null or undefined when calling changeResellerGuestIp().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling changeResellerGuestIp().'
            );
        }

        if (requestParameters['vmid'] == null) {
            throw new runtime.RequiredError(
                'vmid',
                'Required parameter "vmid" was null or undefined when calling changeResellerGuestIp().'
            );
        }

        if (requestParameters['changeResellerGuestIpRequest'] == null) {
            throw new runtime.RequiredError(
                'changeResellerGuestIpRequest',
                'Required parameter "changeResellerGuestIpRequest" was null or undefined when calling changeResellerGuestIp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/guests/{hostId}/{type}/{vmid}/ip`;
        urlPath = urlPath.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters['hostId'])));
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"vmid"}}`, encodeURIComponent(String(requestParameters['vmid'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangeResellerGuestIpRequestToJSON(requestParameters['changeResellerGuestIpRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * `action=change` requires `ip` (must fall inside the target zone\'s range) and assigns it; `action=release` frees the guest\'s current IP for that family. The target zone (`zone_id`, or the guest\'s current single-stack zone if omitted) must be one the calling reseller was granted. Reboot the guest to apply. 
     * Change or release a guest\'s static IP
     */
    async changeResellerGuestIp(requestParameters: ChangeResellerGuestIpOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.changeResellerGuestIpRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ChangeResellerGuestIpOperationTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type ChangeResellerGuestIpOperationTypeEnum = typeof ChangeResellerGuestIpOperationTypeEnum[keyof typeof ChangeResellerGuestIpOperationTypeEnum];
