/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateReseller200Response,
  CreateResellerRequest,
  Envelope,
  ListResellerCustomers200Response,
  UpdateResellerRequest,
} from '../models/index';
import {
    CreateReseller200ResponseFromJSON,
    CreateReseller200ResponseToJSON,
    CreateResellerRequestFromJSON,
    CreateResellerRequestToJSON,
    EnvelopeFromJSON,
    EnvelopeToJSON,
    ListResellerCustomers200ResponseFromJSON,
    ListResellerCustomers200ResponseToJSON,
    UpdateResellerRequestFromJSON,
    UpdateResellerRequestToJSON,
} from '../models/index';

export interface CreateResellerCustomerRequest {
    createResellerRequest: CreateResellerRequest;
}

export interface DeleteResellerCustomerRequest {
    customerId: number;
}

export interface GetResellerCustomerRequest {
    customerId: number;
}

export interface ListResellerCustomersRequest {
    page?: number;
    perPage?: number;
}

export interface ResetResellerCustomerPasswordRequest {
    customerId: number;
}

export interface UpdateResellerCustomerRequest {
    customerId: number;
    updateResellerRequest: UpdateResellerRequest;
}

export interface UpdateResellerCustomerPostRequest {
    customerId: number;
    updateResellerRequest: UpdateResellerRequest;
}

/**
 * 
 */
export class ResellerCustomersApi extends runtime.BaseAPI {

    /**
     * Creates a customer under the calling reseller. Quota-gated (`422` past the reseller\'s plan cap).
     * Create a customer
     */
    async createResellerCustomerRaw(requestParameters: CreateResellerCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateReseller200Response>> {
        if (requestParameters['createResellerRequest'] == null) {
            throw new runtime.RequiredError(
                'createResellerRequest',
                'Required parameter "createResellerRequest" was null or undefined when calling createResellerCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/customers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateResellerRequestToJSON(requestParameters['createResellerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateReseller200ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a customer under the calling reseller. Quota-gated (`422` past the reseller\'s plan cap).
     * Create a customer
     */
    async createResellerCustomer(requestParameters: CreateResellerCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateReseller200Response> {
        const response = await this.createResellerCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refuses (`422`) while the customer still owns guests.
     * Delete a customer
     */
    async deleteResellerCustomerRaw(requestParameters: DeleteResellerCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling deleteResellerCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/customers/{customerId}`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Refuses (`422`) while the customer still owns guests.
     * Delete a customer
     */
    async deleteResellerCustomer(requestParameters: DeleteResellerCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.deleteResellerCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * `404` if this customer does not belong to the calling reseller.
     * Get a customer
     */
    async getResellerCustomerRaw(requestParameters: GetResellerCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling getResellerCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/customers/{customerId}`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * `404` if this customer does not belong to the calling reseller.
     * Get a customer
     */
    async getResellerCustomer(requestParameters: GetResellerCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.getResellerCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List my customers
     */
    async listResellerCustomersRaw(requestParameters: ListResellerCustomersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResellerCustomers200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/customers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResellerCustomers200ResponseFromJSON(jsonValue));
    }

    /**
     * List my customers
     */
    async listResellerCustomers(requestParameters: ListResellerCustomersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResellerCustomers200Response> {
        const response = await this.listResellerCustomersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verifies the reseller token and returns the calling reseller\'s id. Useful for a quick connectivity/credential check.
     * Auth probe
     */
    async resellerPingRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ping`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Verifies the reseller token and returns the calling reseller\'s id. Useful for a quick connectivity/credential check.
     * Auth probe
     */
    async resellerPing(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.resellerPingRaw(initOverrides);
        return await response.value();
    }

    /**
     * Reset a customer\'s password
     */
    async resetResellerCustomerPasswordRaw(requestParameters: ResetResellerCustomerPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling resetResellerCustomerPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/customers/{customerId}/reset-password`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Reset a customer\'s password
     */
    async resetResellerCustomerPassword(requestParameters: ResetResellerCustomerPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.resetResellerCustomerPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a customer
     */
    async updateResellerCustomerRaw(requestParameters: UpdateResellerCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling updateResellerCustomer().'
            );
        }

        if (requestParameters['updateResellerRequest'] == null) {
            throw new runtime.RequiredError(
                'updateResellerRequest',
                'Required parameter "updateResellerRequest" was null or undefined when calling updateResellerCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/customers/{customerId}`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateResellerRequestToJSON(requestParameters['updateResellerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Update a customer
     */
    async updateResellerCustomer(requestParameters: UpdateResellerCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.updateResellerCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Identical to `PATCH /customers/{customerId}`, for clients that cannot send PATCH.
     * Update a customer (POST alias)
     */
    async updateResellerCustomerPostRaw(requestParameters: UpdateResellerCustomerPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling updateResellerCustomerPost().'
            );
        }

        if (requestParameters['updateResellerRequest'] == null) {
            throw new runtime.RequiredError(
                'updateResellerRequest',
                'Required parameter "updateResellerRequest" was null or undefined when calling updateResellerCustomerPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("resellerBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/customers/{customerId}`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateResellerRequestToJSON(requestParameters['updateResellerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Identical to `PATCH /customers/{customerId}`, for clients that cannot send PATCH.
     * Update a customer (POST alias)
     */
    async updateResellerCustomerPost(requestParameters: UpdateResellerCustomerPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.updateResellerCustomerPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
