/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddUserSshKeyRequest,
  AssignUserGuestRequest,
  CreateUser200Response,
  CreateUserRequest,
  Envelope,
  GrantUserIpsRequest,
  ListUsers200Response,
} from '../models/index';
import {
    AddUserSshKeyRequestFromJSON,
    AddUserSshKeyRequestToJSON,
    AssignUserGuestRequestFromJSON,
    AssignUserGuestRequestToJSON,
    CreateUser200ResponseFromJSON,
    CreateUser200ResponseToJSON,
    CreateUserRequestFromJSON,
    CreateUserRequestToJSON,
    EnvelopeFromJSON,
    EnvelopeToJSON,
    GrantUserIpsRequestFromJSON,
    GrantUserIpsRequestToJSON,
    ListUsers200ResponseFromJSON,
    ListUsers200ResponseToJSON,
} from '../models/index';

export interface AddUserSshKeyOperationRequest {
    userId: number;
    addUserSshKeyRequest: AddUserSshKeyRequest;
}

export interface AssignUserGuestOperationRequest {
    userId: number;
    assignUserGuestRequest: AssignUserGuestRequest;
}

export interface CreateUserOperationRequest {
    createUserRequest: CreateUserRequest;
}

export interface DeleteUserRequest {
    userId: number;
}

export interface DeleteUserSshKeyRequest {
    userId: number;
    keyId: number;
}

export interface GrantUserIpsOperationRequest {
    userId: number;
    grantUserIpsRequest: GrantUserIpsRequest;
}

export interface ListUserIpsRequest {
    userId: number;
}

export interface ResetUserPasswordRequest {
    userId: number;
}

export interface RevokeIpRequest {
    ipId: number;
}

export interface UnassignUserGuestRequest {
    userId: number;
    assignUserGuestRequest: AssignUserGuestRequest;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Validates, fingerprints and stores the key (deduped per user). Returns id/name/fingerprint only, never the key body.
     * Add an SSH key to a user
     */
    async addUserSshKeyRaw(requestParameters: AddUserSshKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling addUserSshKey().'
            );
        }

        if (requestParameters['addUserSshKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'addUserSshKeyRequest',
                'Required parameter "addUserSshKeyRequest" was null or undefined when calling addUserSshKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/ssh-keys`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddUserSshKeyRequestToJSON(requestParameters['addUserSshKeyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Validates, fingerprints and stores the key (deduped per user). Returns id/name/fingerprint only, never the key body.
     * Add an SSH key to a user
     */
    async addUserSshKey(requestParameters: AddUserSshKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.addUserSshKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Assigns ownership of a guest to a customer. One owner per guest.
     * Assign guest ownership
     */
    async assignUserGuestRaw(requestParameters: AssignUserGuestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling assignUserGuest().'
            );
        }

        if (requestParameters['assignUserGuestRequest'] == null) {
            throw new runtime.RequiredError(
                'assignUserGuestRequest',
                'Required parameter "assignUserGuestRequest" was null or undefined when calling assignUserGuest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/guests`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssignUserGuestRequestToJSON(requestParameters['assignUserGuestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Assigns ownership of a guest to a customer. One owner per guest.
     * Assign guest ownership
     */
    async assignUserGuest(requestParameters: AssignUserGuestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.assignUserGuestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a customer account with a generated password, returned once in the response. Enqueues a welcome email. 
     * Create a customer user
     */
    async createUserRaw(requestParameters: CreateUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateUser200Response>> {
        if (requestParameters['createUserRequest'] == null) {
            throw new runtime.RequiredError(
                'createUserRequest',
                'Required parameter "createUserRequest" was null or undefined when calling createUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserRequestToJSON(requestParameters['createUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateUser200ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a customer account with a generated password, returned once in the response. Enqueues a welcome email. 
     * Create a customer user
     */
    async createUser(requestParameters: CreateUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateUser200Response> {
        const response = await this.createUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes the customer account and its guest ownership assignments.
     * Delete a customer user
     */
    async deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Deletes the customer account and its guest ownership assignments.
     * Delete a customer user
     */
    async deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.deleteUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete one of a user\'s SSH keys
     */
    async deleteUserSshKeyRaw(requestParameters: DeleteUserSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteUserSshKey().'
            );
        }

        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling deleteUserSshKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/ssh-keys/{keyId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"keyId"}}`, encodeURIComponent(String(requestParameters['keyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Delete one of a user\'s SSH keys
     */
    async deleteUserSshKey(requestParameters: DeleteUserSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.deleteUserSshKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Grant IPs into a customer\'s pool. `mode=zone` (default) reserves the next `count` free addresses from `zone_id`; `mode=specific` grants the given `ids[]` from `zone_id`. 
     * Grant IPs to a customer\'s pool
     */
    async grantUserIpsRaw(requestParameters: GrantUserIpsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling grantUserIps().'
            );
        }

        if (requestParameters['grantUserIpsRequest'] == null) {
            throw new runtime.RequiredError(
                'grantUserIpsRequest',
                'Required parameter "grantUserIpsRequest" was null or undefined when calling grantUserIps().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/ips`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GrantUserIpsRequestToJSON(requestParameters['grantUserIpsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Grant IPs into a customer\'s pool. `mode=zone` (default) reserves the next `count` free addresses from `zone_id`; `mode=specific` grants the given `ids[]` from `zone_id`. 
     * Grant IPs to a customer\'s pool
     */
    async grantUserIps(requestParameters: GrantUserIpsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.grantUserIpsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Every IP owned by the customer (assigned and free), enriched with zone name and family.
     * List a customer\'s owned IP pool
     */
    async listUserIpsRaw(requestParameters: ListUserIpsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listUserIps().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/ips`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Every IP owned by the customer (assigned and free), enriched with zone name and family.
     * List a customer\'s owned IP pool
     */
    async listUserIps(requestParameters: ListUserIpsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.listUserIpsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists customer accounts (never includes secrets). Requires an admin-capable token.
     * List customer users
     */
    async listUsersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListUsers200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListUsers200ResponseFromJSON(jsonValue));
    }

    /**
     * Lists customer accounts (never includes secrets). Requires an admin-capable token.
     * List customer users
     */
    async listUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListUsers200Response> {
        const response = await this.listUsersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Generates a new password for the customer and enqueues a notification email.
     * Reset a customer\'s password
     */
    async resetUserPasswordRaw(requestParameters: ResetUserPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling resetUserPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/reset-password`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Generates a new password for the customer and enqueues a notification email.
     * Reset a customer\'s password
     */
    async resetUserPassword(requestParameters: ResetUserPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.resetUserPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Only an unassigned owned IP can be revoked.
     * Revoke an owned IP back to the admin pool
     */
    async revokeIpRaw(requestParameters: RevokeIpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['ipId'] == null) {
            throw new runtime.RequiredError(
                'ipId',
                'Required parameter "ipId" was null or undefined when calling revokeIp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ip-addresses/{ipId}`;
        urlPath = urlPath.replace(`{${"ipId"}}`, encodeURIComponent(String(requestParameters['ipId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Only an unassigned owned IP can be revoked.
     * Revoke an owned IP back to the admin pool
     */
    async revokeIp(requestParameters: RevokeIpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.revokeIpRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the current owner from a guest.
     * Unassign guest ownership
     */
    async unassignUserGuestRaw(requestParameters: UnassignUserGuestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Envelope>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling unassignUserGuest().'
            );
        }

        if (requestParameters['assignUserGuestRequest'] == null) {
            throw new runtime.RequiredError(
                'assignUserGuestRequest',
                'Required parameter "assignUserGuestRequest" was null or undefined when calling unassignUserGuest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{userId}/guests`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: AssignUserGuestRequestToJSON(requestParameters['assignUserGuestRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnvelopeFromJSON(jsonValue));
    }

    /**
     * Removes the current owner from a guest.
     * Unassign guest ownership
     */
    async unassignUserGuest(requestParameters: UnassignUserGuestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Envelope> {
        const response = await this.unassignUserGuestRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
