/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAlertRuleRequest
 */
export interface CreateAlertRuleRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAlertRuleRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAlertRuleRequest
     */
    type: CreateAlertRuleRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateAlertRuleRequest
     */
    severity: CreateAlertRuleRequestSeverityEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateAlertRuleRequest
     */
    channels: Array<CreateAlertRuleRequestChannelsEnum>;
    /**
     * 
     * @type {number}
     * @memberof CreateAlertRuleRequest
     */
    threshold?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateAlertRuleRequest
     */
    durationMinutes: number;
    /**
     * 
     * @type {number}
     * @memberof CreateAlertRuleRequest
     */
    hostId?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateAlertRuleRequest
     */
    node?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAlertRuleRequest
     */
    guestType?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateAlertRuleRequest
     */
    vmid?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateAlertRuleRequest
     */
    cooldownMinutes?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CreateAlertRuleRequest
     */
    enabled?: boolean;
}


/**
 * @export
 */
export const CreateAlertRuleRequestTypeEnum = {
    GuestDown: 'guest_down',
    NodeUnreachable: 'node_unreachable',
    CpuHigh: 'cpu_high',
    MemHigh: 'mem_high',
    DiskHigh: 'disk_high',
    AgentUnhealthy: 'agent_unhealthy',
    PlanTraffic: 'plan_traffic',
    PlanExpiry: 'plan_expiry'
} as const;
export type CreateAlertRuleRequestTypeEnum = typeof CreateAlertRuleRequestTypeEnum[keyof typeof CreateAlertRuleRequestTypeEnum];

/**
 * @export
 */
export const CreateAlertRuleRequestSeverityEnum = {
    Info: 'info',
    Warning: 'warning',
    Critical: 'critical'
} as const;
export type CreateAlertRuleRequestSeverityEnum = typeof CreateAlertRuleRequestSeverityEnum[keyof typeof CreateAlertRuleRequestSeverityEnum];

/**
 * @export
 */
export const CreateAlertRuleRequestChannelsEnum = {
    Inbox: 'inbox',
    Email: 'email',
    Webhook: 'webhook'
} as const;
export type CreateAlertRuleRequestChannelsEnum = typeof CreateAlertRuleRequestChannelsEnum[keyof typeof CreateAlertRuleRequestChannelsEnum];


/**
 * Check if a given object implements the CreateAlertRuleRequest interface.
 */
export function instanceOfCreateAlertRuleRequest(value: object): value is CreateAlertRuleRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('severity' in value) || value['severity'] === undefined) return false;
    if (!('channels' in value) || value['channels'] === undefined) return false;
    if (!('durationMinutes' in value) || value['durationMinutes'] === undefined) return false;
    return true;
}

export function CreateAlertRuleRequestFromJSON(json: any): CreateAlertRuleRequest {
    return CreateAlertRuleRequestFromJSONTyped(json, false);
}

export function CreateAlertRuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAlertRuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'],
        'severity': json['severity'],
        'channels': json['channels'],
        'threshold': json['threshold'] == null ? undefined : json['threshold'],
        'durationMinutes': json['duration_minutes'],
        'hostId': json['host_id'] == null ? undefined : json['host_id'],
        'node': json['node'] == null ? undefined : json['node'],
        'guestType': json['guest_type'] == null ? undefined : json['guest_type'],
        'vmid': json['vmid'] == null ? undefined : json['vmid'],
        'cooldownMinutes': json['cooldown_minutes'] == null ? undefined : json['cooldown_minutes'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function CreateAlertRuleRequestToJSON(json: any): CreateAlertRuleRequest {
    return CreateAlertRuleRequestToJSONTyped(json, false);
}

export function CreateAlertRuleRequestToJSONTyped(value?: CreateAlertRuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'severity': value['severity'],
        'channels': value['channels'],
        'threshold': value['threshold'],
        'duration_minutes': value['durationMinutes'],
        'host_id': value['hostId'],
        'node': value['node'],
        'guest_type': value['guestType'],
        'vmid': value['vmid'],
        'cooldown_minutes': value['cooldownMinutes'],
        'enabled': value['enabled'],
    };
}

