/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGuestFirewallRuleRequest
 */
export interface CreateGuestFirewallRuleRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateGuestFirewallRuleRequest
     */
    node: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGuestFirewallRuleRequest
     */
    direction: CreateGuestFirewallRuleRequestDirectionEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateGuestFirewallRuleRequest
     */
    action: CreateGuestFirewallRuleRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateGuestFirewallRuleRequest
     */
    proto?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGuestFirewallRuleRequest
     */
    dport?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGuestFirewallRuleRequest
     */
    sport?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGuestFirewallRuleRequest
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGuestFirewallRuleRequest
     */
    dest?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGuestFirewallRuleRequest
     */
    comment?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateGuestFirewallRuleRequest
     */
    enabled?: boolean;
}


/**
 * @export
 */
export const CreateGuestFirewallRuleRequestDirectionEnum = {
    In: 'in',
    Out: 'out'
} as const;
export type CreateGuestFirewallRuleRequestDirectionEnum = typeof CreateGuestFirewallRuleRequestDirectionEnum[keyof typeof CreateGuestFirewallRuleRequestDirectionEnum];

/**
 * @export
 */
export const CreateGuestFirewallRuleRequestActionEnum = {
    Accept: 'ACCEPT',
    Drop: 'DROP',
    Reject: 'REJECT'
} as const;
export type CreateGuestFirewallRuleRequestActionEnum = typeof CreateGuestFirewallRuleRequestActionEnum[keyof typeof CreateGuestFirewallRuleRequestActionEnum];


/**
 * Check if a given object implements the CreateGuestFirewallRuleRequest interface.
 */
export function instanceOfCreateGuestFirewallRuleRequest(value: object): value is CreateGuestFirewallRuleRequest {
    if (!('node' in value) || value['node'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function CreateGuestFirewallRuleRequestFromJSON(json: any): CreateGuestFirewallRuleRequest {
    return CreateGuestFirewallRuleRequestFromJSONTyped(json, false);
}

export function CreateGuestFirewallRuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGuestFirewallRuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'node': json['node'],
        'direction': json['direction'],
        'action': json['action'],
        'proto': json['proto'] == null ? undefined : json['proto'],
        'dport': json['dport'] == null ? undefined : json['dport'],
        'sport': json['sport'] == null ? undefined : json['sport'],
        'source': json['source'] == null ? undefined : json['source'],
        'dest': json['dest'] == null ? undefined : json['dest'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function CreateGuestFirewallRuleRequestToJSON(json: any): CreateGuestFirewallRuleRequest {
    return CreateGuestFirewallRuleRequestToJSONTyped(json, false);
}

export function CreateGuestFirewallRuleRequestToJSONTyped(value?: CreateGuestFirewallRuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'node': value['node'],
        'direction': value['direction'],
        'action': value['action'],
        'proto': value['proto'],
        'dport': value['dport'],
        'sport': value['sport'],
        'source': value['source'],
        'dest': value['dest'],
        'comment': value['comment'],
        'enabled': value['enabled'],
    };
}

