/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateHostRequest
 */
export interface CreateHostRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateHostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateHostRequest
     */
    hostname: string;
    /**
     * 
     * @type {number}
     * @memberof CreateHostRequest
     */
    port?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateHostRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateHostRequest
     */
    realm?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateHostRequest
     */
    password: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateHostRequest
     */
    verifyTls?: boolean;
}

/**
 * Check if a given object implements the CreateHostRequest interface.
 */
export function instanceOfCreateHostRequest(value: object): value is CreateHostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function CreateHostRequestFromJSON(json: any): CreateHostRequest {
    return CreateHostRequestFromJSONTyped(json, false);
}

export function CreateHostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateHostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'hostname': json['hostname'],
        'port': json['port'] == null ? undefined : json['port'],
        'username': json['username'] == null ? undefined : json['username'],
        'realm': json['realm'] == null ? undefined : json['realm'],
        'password': json['password'],
        'verifyTls': json['verify_tls'] == null ? undefined : json['verify_tls'],
    };
}

export function CreateHostRequestToJSON(json: any): CreateHostRequest {
    return CreateHostRequestToJSONTyped(json, false);
}

export function CreateHostRequestToJSONTyped(value?: CreateHostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'hostname': value['hostname'],
        'port': value['port'],
        'username': value['username'],
        'realm': value['realm'],
        'password': value['password'],
        'verify_tls': value['verifyTls'],
    };
}

