/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResellerGuestRequest
 */
export interface CreateResellerGuestRequest {
    [key: string]: any | any;
    /**
     * One of the calling reseller's own customer ids.
     * @type {number}
     * @memberof CreateResellerGuestRequest
     */
    ownerId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateResellerGuestRequest
     */
    hostId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateResellerGuestRequest
     */
    node: string;
    /**
     * 
     * @type {string}
     * @memberof CreateResellerGuestRequest
     */
    type: CreateResellerGuestRequestTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateResellerGuestRequest
     */
    vmid: number;
    /**
     * 
     * @type {string}
     * @memberof CreateResellerGuestRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateResellerGuestRequest
     */
    storage: string;
    /**
     * 
     * @type {number}
     * @memberof CreateResellerGuestRequest
     */
    planId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateResellerGuestRequest
     */
    cores?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateResellerGuestRequest
     */
    memoryMb?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateResellerGuestRequest
     */
    diskGb?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateResellerGuestRequest
     */
    bridge?: string;
    /**
     * qemu `tpl:<id>` or lxc CT template volid.
     * @type {string}
     * @memberof CreateResellerGuestRequest
     */
    osTemplate?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateResellerGuestRequest
     */
    ipSource?: CreateResellerGuestRequestIpSourceEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateResellerGuestRequest
     */
    ipv4ZoneId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateResellerGuestRequest
     */
    ipv6ZoneId?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateResellerGuestRequest
     */
    password?: string;
}


/**
 * @export
 */
export const CreateResellerGuestRequestTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type CreateResellerGuestRequestTypeEnum = typeof CreateResellerGuestRequestTypeEnum[keyof typeof CreateResellerGuestRequestTypeEnum];

/**
 * @export
 */
export const CreateResellerGuestRequestIpSourceEnum = {
    Dhcp: 'dhcp',
    Zone: 'zone'
} as const;
export type CreateResellerGuestRequestIpSourceEnum = typeof CreateResellerGuestRequestIpSourceEnum[keyof typeof CreateResellerGuestRequestIpSourceEnum];


/**
 * Check if a given object implements the CreateResellerGuestRequest interface.
 */
export function instanceOfCreateResellerGuestRequest(value: object): value is CreateResellerGuestRequest {
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('hostId' in value) || value['hostId'] === undefined) return false;
    if (!('node' in value) || value['node'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('vmid' in value) || value['vmid'] === undefined) return false;
    if (!('storage' in value) || value['storage'] === undefined) return false;
    return true;
}

export function CreateResellerGuestRequestFromJSON(json: any): CreateResellerGuestRequest {
    return CreateResellerGuestRequestFromJSONTyped(json, false);
}

export function CreateResellerGuestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResellerGuestRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'ownerId': json['owner_id'],
        'hostId': json['host_id'],
        'node': json['node'],
        'type': json['type'],
        'vmid': json['vmid'],
        'name': json['name'] == null ? undefined : json['name'],
        'storage': json['storage'],
        'planId': json['plan_id'] == null ? undefined : json['plan_id'],
        'cores': json['cores'] == null ? undefined : json['cores'],
        'memoryMb': json['memory_mb'] == null ? undefined : json['memory_mb'],
        'diskGb': json['disk_gb'] == null ? undefined : json['disk_gb'],
        'bridge': json['bridge'] == null ? undefined : json['bridge'],
        'osTemplate': json['os_template'] == null ? undefined : json['os_template'],
        'ipSource': json['ip_source'] == null ? undefined : json['ip_source'],
        'ipv4ZoneId': json['ipv4_zone_id'] == null ? undefined : json['ipv4_zone_id'],
        'ipv6ZoneId': json['ipv6_zone_id'] == null ? undefined : json['ipv6_zone_id'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function CreateResellerGuestRequestToJSON(json: any): CreateResellerGuestRequest {
    return CreateResellerGuestRequestToJSONTyped(json, false);
}

export function CreateResellerGuestRequestToJSONTyped(value?: CreateResellerGuestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'owner_id': value['ownerId'],
        'host_id': value['hostId'],
        'node': value['node'],
        'type': value['type'],
        'vmid': value['vmid'],
        'name': value['name'],
        'storage': value['storage'],
        'plan_id': value['planId'],
        'cores': value['cores'],
        'memory_mb': value['memoryMb'],
        'disk_gb': value['diskGb'],
        'bridge': value['bridge'],
        'os_template': value['osTemplate'],
        'ip_source': value['ipSource'],
        'ipv4_zone_id': value['ipv4ZoneId'],
        'ipv6_zone_id': value['ipv6ZoneId'],
        'password': value['password'],
    };
}

