/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Common fields apply to both types. QEMU additionally requires `os_template`. LXC requires exactly one of `lxc_template_id` or `os_template`. `password` is required unless at least one SSH key is present, either via `ssh_keys[]` or an `owner_id` with stored keys.
 * 
 * @export
 * @interface GuestCreateRequest
 */
export interface GuestCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof GuestCreateRequest
     */
    type: GuestCreateRequestTypeEnum;
    /**
     * Target PVE node name.
     * @type {string}
     * @memberof GuestCreateRequest
     */
    node: string;
    /**
     * A positive, free VMID. Get one from GET /hosts/{hostId}/next-vmid.
     * @type {number}
     * @memberof GuestCreateRequest
     */
    vmid: number;
    /**
     * Guest name/hostname. Defaults to vm-<vmid> or ct-<vmid>.
     * @type {string}
     * @memberof GuestCreateRequest
     */
    name?: string;
    /**
     * A plan id from GET /hosts/{hostId}/plans. Fills and locks cores/memory_mb/disk_gb.
     * @type {number}
     * @memberof GuestCreateRequest
     */
    planId?: number;
    /**
     * Explicit spec when no plan_id is given.
     * @type {number}
     * @memberof GuestCreateRequest
     */
    cores?: number;
    /**
     * Explicit spec when no plan_id is given.
     * @type {number}
     * @memberof GuestCreateRequest
     */
    memoryMb?: number;
    /**
     * Explicit spec when no plan_id is given.
     * @type {number}
     * @memberof GuestCreateRequest
     */
    diskGb?: number;
    /**
     * Storage id for the root disk, from GET /hosts/{hostId}/storages.
     * @type {string}
     * @memberof GuestCreateRequest
     */
    storage?: string;
    /**
     * Network bridge, from GET /hosts/{hostId}/networks.
     * @type {string}
     * @memberof GuestCreateRequest
     */
    bridge?: string;
    /**
     * Required for QEMU as tpl:<id> from GET /hosts/{hostId}/os-templates. For LXC, an alternative to lxc_template_id, a raw vztmpl volid from GET /hosts/{hostId}/ct-templates.
     * 
     * @type {string}
     * @memberof GuestCreateRequest
     */
    osTemplate?: string;
    /**
     * LXC only, a managed CT template id from GET /hosts/{hostId}/ct-templates.
     * @type {number}
     * @memberof GuestCreateRequest
     */
    lxcTemplateId?: number;
    /**
     * dhcp (default) or zone:<id> from GET /hosts/{hostId}/ip-zones to allocate a static IP.
     * @type {string}
     * @memberof GuestCreateRequest
     */
    ipSource?: string;
    /**
     * Root password. Required unless an SSH key is present.
     * @type {string}
     * @memberof GuestCreateRequest
     */
    password?: string;
    /**
     * Public key bodies, merged with the owner's stored keys.
     * @type {Array<string>}
     * @memberof GuestCreateRequest
     */
    sshKeys?: Array<string>;
    /**
     * Assigns ownership. The owner's stored SSH keys are auto-injected.
     * @type {number}
     * @memberof GuestCreateRequest
     */
    ownerId?: number;
    /**
     * Max snapshots for this guest.
     * @type {number}
     * @memberof GuestCreateRequest
     */
    snapshotLimit?: number;
    /**
     * Firewall preset ids to apply.
     * @type {Array<number>}
     * @memberof GuestCreateRequest
     */
    firewallPresets?: Array<number>;
    /**
     * Parallel array with extra_size/extra_mount, additional disk storage ids.
     * @type {Array<string>}
     * @memberof GuestCreateRequest
     */
    extraStorage?: Array<string>;
    /**
     * Parallel array with extra_storage/extra_mount, additional disk sizes in GB.
     * @type {Array<number>}
     * @memberof GuestCreateRequest
     */
    extraSize?: Array<number>;
    /**
     * Parallel array with extra_storage/extra_size, LXC-only mount paths. Must be absolute paths; blank defaults to /mnt/disk<N>.
     * 
     * @type {Array<string>}
     * @memberof GuestCreateRequest
     */
    extraMount?: Array<string>;
    /**
     * LXC only. Create an unprivileged container. Omitted keeps PVE's default (privileged). For Docker in an unprivileged container also set nesting + keyctl.
     * 
     * @type {boolean}
     * @memberof GuestCreateRequest
     */
    unprivileged?: boolean;
    /**
     * LXC only. Adds nesting=1 to the container features (run Docker / systemd / nested containers).
     * @type {boolean}
     * @memberof GuestCreateRequest
     */
    nesting?: boolean;
    /**
     * LXC only. Adds keyctl=1 (required for Docker inside an unprivileged container).
     * @type {boolean}
     * @memberof GuestCreateRequest
     */
    keyctl?: boolean;
    /**
     * LXC only. Adds fuse=1 (allow FUSE mounts inside the container).
     * @type {boolean}
     * @memberof GuestCreateRequest
     */
    fuse?: boolean;
    /**
     * LXC only. Comma/semicolon list of mount types to allow (allow-listed: nfs, cifs). Invalid types return 422.
     * @type {string}
     * @memberof GuestCreateRequest
     */
    mount?: string;
    /**
     * QEMU only. Firmware. ovmf (UEFI) also allocates an EFI disk on the chosen storage. Unrecognised values are ignored.
     * @type {string}
     * @memberof GuestCreateRequest
     */
    bios?: GuestCreateRequestBiosEnum;
    /**
     * QEMU only. Machine type. Unrecognised values are ignored.
     * @type {string}
     * @memberof GuestCreateRequest
     */
    machine?: GuestCreateRequestMachineEnum;
    /**
     * QEMU only. CPU type. Unrecognised values are ignored.
     * @type {string}
     * @memberof GuestCreateRequest
     */
    cpu?: GuestCreateRequestCpuEnum;
    /**
     * QEMU only. Display adapter. Unrecognised values are ignored.
     * @type {string}
     * @memberof GuestCreateRequest
     */
    vga?: GuestCreateRequestVgaEnum;
}


/**
 * @export
 */
export const GuestCreateRequestTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type GuestCreateRequestTypeEnum = typeof GuestCreateRequestTypeEnum[keyof typeof GuestCreateRequestTypeEnum];

/**
 * @export
 */
export const GuestCreateRequestBiosEnum = {
    Seabios: 'seabios',
    Ovmf: 'ovmf'
} as const;
export type GuestCreateRequestBiosEnum = typeof GuestCreateRequestBiosEnum[keyof typeof GuestCreateRequestBiosEnum];

/**
 * @export
 */
export const GuestCreateRequestMachineEnum = {
    I440fx: 'i440fx',
    Q35: 'q35'
} as const;
export type GuestCreateRequestMachineEnum = typeof GuestCreateRequestMachineEnum[keyof typeof GuestCreateRequestMachineEnum];

/**
 * @export
 */
export const GuestCreateRequestCpuEnum = {
    Kvm64: 'kvm64',
    Host: 'host',
    Qemu64: 'qemu64',
    X8664V2: 'x86-64-v2',
    X8664V2Aes: 'x86-64-v2-AES',
    X8664V3: 'x86-64-v3',
    X8664V4: 'x86-64-v4'
} as const;
export type GuestCreateRequestCpuEnum = typeof GuestCreateRequestCpuEnum[keyof typeof GuestCreateRequestCpuEnum];

/**
 * @export
 */
export const GuestCreateRequestVgaEnum = {
    Std: 'std',
    Qxl: 'qxl',
    Virtio: 'virtio',
    Vmware: 'vmware',
    Cirrus: 'cirrus',
    Serial0: 'serial0',
    None: 'none'
} as const;
export type GuestCreateRequestVgaEnum = typeof GuestCreateRequestVgaEnum[keyof typeof GuestCreateRequestVgaEnum];


/**
 * Check if a given object implements the GuestCreateRequest interface.
 */
export function instanceOfGuestCreateRequest(value: object): value is GuestCreateRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('node' in value) || value['node'] === undefined) return false;
    if (!('vmid' in value) || value['vmid'] === undefined) return false;
    return true;
}

export function GuestCreateRequestFromJSON(json: any): GuestCreateRequest {
    return GuestCreateRequestFromJSONTyped(json, false);
}

export function GuestCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuestCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'node': json['node'],
        'vmid': json['vmid'],
        'name': json['name'] == null ? undefined : json['name'],
        'planId': json['plan_id'] == null ? undefined : json['plan_id'],
        'cores': json['cores'] == null ? undefined : json['cores'],
        'memoryMb': json['memory_mb'] == null ? undefined : json['memory_mb'],
        'diskGb': json['disk_gb'] == null ? undefined : json['disk_gb'],
        'storage': json['storage'] == null ? undefined : json['storage'],
        'bridge': json['bridge'] == null ? undefined : json['bridge'],
        'osTemplate': json['os_template'] == null ? undefined : json['os_template'],
        'lxcTemplateId': json['lxc_template_id'] == null ? undefined : json['lxc_template_id'],
        'ipSource': json['ip_source'] == null ? undefined : json['ip_source'],
        'password': json['password'] == null ? undefined : json['password'],
        'sshKeys': json['ssh_keys'] == null ? undefined : json['ssh_keys'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'snapshotLimit': json['snapshot_limit'] == null ? undefined : json['snapshot_limit'],
        'firewallPresets': json['firewall_presets'] == null ? undefined : json['firewall_presets'],
        'extraStorage': json['extra_storage'] == null ? undefined : json['extra_storage'],
        'extraSize': json['extra_size'] == null ? undefined : json['extra_size'],
        'extraMount': json['extra_mount'] == null ? undefined : json['extra_mount'],
        'unprivileged': json['unprivileged'] == null ? undefined : json['unprivileged'],
        'nesting': json['nesting'] == null ? undefined : json['nesting'],
        'keyctl': json['keyctl'] == null ? undefined : json['keyctl'],
        'fuse': json['fuse'] == null ? undefined : json['fuse'],
        'mount': json['mount'] == null ? undefined : json['mount'],
        'bios': json['bios'] == null ? undefined : json['bios'],
        'machine': json['machine'] == null ? undefined : json['machine'],
        'cpu': json['cpu'] == null ? undefined : json['cpu'],
        'vga': json['vga'] == null ? undefined : json['vga'],
    };
}

export function GuestCreateRequestToJSON(json: any): GuestCreateRequest {
    return GuestCreateRequestToJSONTyped(json, false);
}

export function GuestCreateRequestToJSONTyped(value?: GuestCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'node': value['node'],
        'vmid': value['vmid'],
        'name': value['name'],
        'plan_id': value['planId'],
        'cores': value['cores'],
        'memory_mb': value['memoryMb'],
        'disk_gb': value['diskGb'],
        'storage': value['storage'],
        'bridge': value['bridge'],
        'os_template': value['osTemplate'],
        'lxc_template_id': value['lxcTemplateId'],
        'ip_source': value['ipSource'],
        'password': value['password'],
        'ssh_keys': value['sshKeys'],
        'owner_id': value['ownerId'],
        'snapshot_limit': value['snapshotLimit'],
        'firewall_presets': value['firewallPresets'],
        'extra_storage': value['extraStorage'],
        'extra_size': value['extraSize'],
        'extra_mount': value['extraMount'],
        'unprivileged': value['unprivileged'],
        'nesting': value['nesting'],
        'keyctl': value['keyctl'],
        'fuse': value['fuse'],
        'mount': value['mount'],
        'bios': value['bios'],
        'machine': value['machine'],
        'cpu': value['cpu'],
        'vga': value['vga'],
    };
}

