/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuestListItem
 */
export interface GuestListItem {
    /**
     * 
     * @type {number}
     * @memberof GuestListItem
     */
    hostId?: number;
    /**
     * 
     * @type {string}
     * @memberof GuestListItem
     */
    host?: string;
    /**
     * 
     * @type {string}
     * @memberof GuestListItem
     */
    node?: string;
    /**
     * 
     * @type {number}
     * @memberof GuestListItem
     */
    vmid?: number;
    /**
     * 
     * @type {string}
     * @memberof GuestListItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GuestListItem
     */
    type?: GuestListItemTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GuestListItem
     */
    status?: string;
    /**
     * The PVE ostype.
     * @type {string}
     * @memberof GuestListItem
     */
    os?: string;
    /**
     * 
     * @type {string}
     * @memberof GuestListItem
     */
    ip?: string;
    /**
     * 
     * @type {number}
     * @memberof GuestListItem
     */
    cores?: number;
    /**
     * Configured max memory in bytes.
     * @type {number}
     * @memberof GuestListItem
     */
    mem?: number;
    /**
     * Configured max disk in bytes.
     * @type {number}
     * @memberof GuestListItem
     */
    storage?: number;
    /**
     * Whether the QEMU guest agent is enabled. Null for LXC or when unknown.
     * @type {boolean}
     * @memberof GuestListItem
     */
    qemuAgent?: boolean | null;
    /**
     * PVE tags, semicolon-joined (empty string when none). Searchable in the panel.
     * @type {string}
     * @memberof GuestListItem
     */
    tags?: string;
}


/**
 * @export
 */
export const GuestListItemTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type GuestListItemTypeEnum = typeof GuestListItemTypeEnum[keyof typeof GuestListItemTypeEnum];


/**
 * Check if a given object implements the GuestListItem interface.
 */
export function instanceOfGuestListItem(value: object): value is GuestListItem {
    return true;
}

export function GuestListItemFromJSON(json: any): GuestListItem {
    return GuestListItemFromJSONTyped(json, false);
}

export function GuestListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuestListItem {
    if (json == null) {
        return json;
    }
    return {
        
        'hostId': json['host_id'] == null ? undefined : json['host_id'],
        'host': json['host'] == null ? undefined : json['host'],
        'node': json['node'] == null ? undefined : json['node'],
        'vmid': json['vmid'] == null ? undefined : json['vmid'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'os': json['os'] == null ? undefined : json['os'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'cores': json['cores'] == null ? undefined : json['cores'],
        'mem': json['mem'] == null ? undefined : json['mem'],
        'storage': json['storage'] == null ? undefined : json['storage'],
        'qemuAgent': json['qemu_agent'] == null ? undefined : json['qemu_agent'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function GuestListItemToJSON(json: any): GuestListItem {
    return GuestListItemToJSONTyped(json, false);
}

export function GuestListItemToJSONTyped(value?: GuestListItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'host_id': value['hostId'],
        'host': value['host'],
        'node': value['node'],
        'vmid': value['vmid'],
        'name': value['name'],
        'type': value['type'],
        'status': value['status'],
        'os': value['os'],
        'ip': value['ip'],
        'cores': value['cores'],
        'mem': value['mem'],
        'storage': value['storage'],
        'qemu_agent': value['qemuAgent'],
        'tags': value['tags'],
    };
}

