/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IpZone
 */
export interface IpZone {
    /**
     * 
     * @type {number}
     * @memberof IpZone
     */
    id?: number;
    /**
     * The exact ip_source value to allocate a static IP.
     * @type {string}
     * @memberof IpZone
     */
    ref?: string;
    /**
     * 
     * @type {string}
     * @memberof IpZone
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IpZone
     */
    family?: IpZoneFamilyEnum;
    /**
     * 
     * @type {string}
     * @memberof IpZone
     */
    bridge?: string;
    /**
     * 
     * @type {string}
     * @memberof IpZone
     */
    cidr?: string;
    /**
     * 
     * @type {string}
     * @memberof IpZone
     */
    gateway?: string;
    /**
     * 
     * @type {string}
     * @memberof IpZone
     */
    vlan?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IpZone
     */
    isActive?: boolean;
}


/**
 * @export
 */
export const IpZoneFamilyEnum = {
    Ipv4: 'ipv4',
    Ipv6: 'ipv6'
} as const;
export type IpZoneFamilyEnum = typeof IpZoneFamilyEnum[keyof typeof IpZoneFamilyEnum];


/**
 * Check if a given object implements the IpZone interface.
 */
export function instanceOfIpZone(value: object): value is IpZone {
    return true;
}

export function IpZoneFromJSON(json: any): IpZone {
    return IpZoneFromJSONTyped(json, false);
}

export function IpZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): IpZone {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'ref': json['ref'] == null ? undefined : json['ref'],
        'name': json['name'] == null ? undefined : json['name'],
        'family': json['family'] == null ? undefined : json['family'],
        'bridge': json['bridge'] == null ? undefined : json['bridge'],
        'cidr': json['cidr'] == null ? undefined : json['cidr'],
        'gateway': json['gateway'] == null ? undefined : json['gateway'],
        'vlan': json['vlan'] == null ? undefined : json['vlan'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function IpZoneToJSON(json: any): IpZone {
    return IpZoneToJSONTyped(json, false);
}

export function IpZoneToJSONTyped(value?: IpZone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ref': value['ref'],
        'name': value['name'],
        'family': value['family'],
        'bridge': value['bridge'],
        'cidr': value['cidr'],
        'gateway': value['gateway'],
        'vlan': value['vlan'],
        'is_active': value['isActive'],
    };
}

