/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { GuestListItem } from './GuestListItem';
import {
    GuestListItemFromJSON,
    GuestListItemFromJSONTyped,
    GuestListItemToJSON,
    GuestListItemToJSONTyped,
} from './GuestListItem';

/**
 * 
 * @export
 * @interface ListGuests200Response
 */
export interface ListGuests200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListGuests200Response
     */
    success: boolean;
    /**
     * 
     * @type {Array<GuestListItem>}
     * @memberof ListGuests200Response
     */
    data: Array<GuestListItem>;
    /**
     * A human-readable error message, null on success.
     * @type {string}
     * @memberof ListGuests200Response
     */
    error: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof ListGuests200Response
     */
    meta?: PaginationMeta;
}

/**
 * Check if a given object implements the ListGuests200Response interface.
 */
export function instanceOfListGuests200Response(value: object): value is ListGuests200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ListGuests200ResponseFromJSON(json: any): ListGuests200Response {
    return ListGuests200ResponseFromJSONTyped(json, false);
}

export function ListGuests200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListGuests200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(GuestListItemFromJSON)),
        'error': json['error'],
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    };
}

export function ListGuests200ResponseToJSON(json: any): ListGuests200Response {
    return ListGuests200ResponseToJSONTyped(json, false);
}

export function ListGuests200ResponseToJSONTyped(value?: ListGuests200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(GuestListItemToJSON)),
        'error': value['error'],
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

