/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NetworkInterface
 */
export interface NetworkInterface {
    /**
     * 
     * @type {string}
     * @memberof NetworkInterface
     */
    iface?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkInterface
     */
    node?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkInterface
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkInterface
     */
    role?: NetworkInterfaceRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof NetworkInterface
     */
    cidr?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkInterface
     */
    gateway?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkInterface
     */
    ports?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NetworkInterface
     */
    active?: boolean;
}


/**
 * @export
 */
export const NetworkInterfaceRoleEnum = {
    Wan: 'WAN',
    Private: 'Private',
    Internal: 'Internal',
    Other: 'Other'
} as const;
export type NetworkInterfaceRoleEnum = typeof NetworkInterfaceRoleEnum[keyof typeof NetworkInterfaceRoleEnum];


/**
 * Check if a given object implements the NetworkInterface interface.
 */
export function instanceOfNetworkInterface(value: object): value is NetworkInterface {
    return true;
}

export function NetworkInterfaceFromJSON(json: any): NetworkInterface {
    return NetworkInterfaceFromJSONTyped(json, false);
}

export function NetworkInterfaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkInterface {
    if (json == null) {
        return json;
    }
    return {
        
        'iface': json['iface'] == null ? undefined : json['iface'],
        'node': json['node'] == null ? undefined : json['node'],
        'type': json['type'] == null ? undefined : json['type'],
        'role': json['role'] == null ? undefined : json['role'],
        'cidr': json['cidr'] == null ? undefined : json['cidr'],
        'gateway': json['gateway'] == null ? undefined : json['gateway'],
        'ports': json['ports'] == null ? undefined : json['ports'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function NetworkInterfaceToJSON(json: any): NetworkInterface {
    return NetworkInterfaceToJSONTyped(json, false);
}

export function NetworkInterfaceToJSONTyped(value?: NetworkInterface | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iface': value['iface'],
        'node': value['node'],
        'type': value['type'],
        'role': value['role'],
        'cidr': value['cidr'],
        'gateway': value['gateway'],
        'ports': value['ports'],
        'active': value['active'],
    };
}

