/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A live PVE node summary as returned by Proxmox's own `nodes` endpoint, passed through with minimal shaping.
 * 
 * @export
 * @interface NodeSummary
 */
export interface NodeSummary {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof NodeSummary
     */
    node?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeSummary
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof NodeSummary
     */
    cpu?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeSummary
     */
    maxcpu?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeSummary
     */
    mem?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeSummary
     */
    maxmem?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeSummary
     */
    disk?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeSummary
     */
    maxdisk?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeSummary
     */
    uptime?: number;
}

/**
 * Check if a given object implements the NodeSummary interface.
 */
export function instanceOfNodeSummary(value: object): value is NodeSummary {
    return true;
}

export function NodeSummaryFromJSON(json: any): NodeSummary {
    return NodeSummaryFromJSONTyped(json, false);
}

export function NodeSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeSummary {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'node': json['node'] == null ? undefined : json['node'],
        'status': json['status'] == null ? undefined : json['status'],
        'cpu': json['cpu'] == null ? undefined : json['cpu'],
        'maxcpu': json['maxcpu'] == null ? undefined : json['maxcpu'],
        'mem': json['mem'] == null ? undefined : json['mem'],
        'maxmem': json['maxmem'] == null ? undefined : json['maxmem'],
        'disk': json['disk'] == null ? undefined : json['disk'],
        'maxdisk': json['maxdisk'] == null ? undefined : json['maxdisk'],
        'uptime': json['uptime'] == null ? undefined : json['uptime'],
    };
}

export function NodeSummaryToJSON(json: any): NodeSummary {
    return NodeSummaryToJSONTyped(json, false);
}

export function NodeSummaryToJSONTyped(value?: NodeSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'node': value['node'],
        'status': value['status'],
        'cpu': value['cpu'],
        'maxcpu': value['maxcpu'],
        'mem': value['mem'],
        'maxmem': value['maxmem'],
        'disk': value['disk'],
        'maxdisk': value['maxdisk'],
        'uptime': value['uptime'],
    };
}

