/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Plan
 */
export interface Plan {
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    cores?: number;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    memoryMb?: number;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    diskGb?: number;
    /**
     * Monthly traffic limit. 0 means unlimited.
     * @type {number}
     * @memberof Plan
     */
    trafficLimitGb?: number;
    /**
     * Expiry in days. 0 means unlimited.
     * @type {number}
     * @memberof Plan
     */
    runtimeDays?: number;
    /**
     * Grace period before auto-delete after expiry.
     * @type {number}
     * @memberof Plan
     */
    graceDays?: number;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    snapshotLimit?: number;
}

/**
 * Check if a given object implements the Plan interface.
 */
export function instanceOfPlan(value: object): value is Plan {
    return true;
}

export function PlanFromJSON(json: any): Plan {
    return PlanFromJSONTyped(json, false);
}

export function PlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): Plan {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'cores': json['cores'] == null ? undefined : json['cores'],
        'memoryMb': json['memory_mb'] == null ? undefined : json['memory_mb'],
        'diskGb': json['disk_gb'] == null ? undefined : json['disk_gb'],
        'trafficLimitGb': json['traffic_limit_gb'] == null ? undefined : json['traffic_limit_gb'],
        'runtimeDays': json['runtime_days'] == null ? undefined : json['runtime_days'],
        'graceDays': json['grace_days'] == null ? undefined : json['grace_days'],
        'snapshotLimit': json['snapshot_limit'] == null ? undefined : json['snapshot_limit'],
    };
}

export function PlanToJSON(json: any): Plan {
    return PlanToJSONTyped(json, false);
}

export function PlanToJSONTyped(value?: Plan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'cores': value['cores'],
        'memory_mb': value['memoryMb'],
        'disk_gb': value['diskGb'],
        'traffic_limit_gb': value['trafficLimitGb'],
        'runtime_days': value['runtimeDays'],
        'grace_days': value['graceDays'],
        'snapshot_limit': value['snapshotLimit'],
    };
}

