/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProvisioningJob
 */
export interface ProvisioningJob {
    /**
     * 
     * @type {number}
     * @memberof ProvisioningJob
     */
    id?: number;
    /**
     * One of create, reinstall, delete, power.
     * @type {string}
     * @memberof ProvisioningJob
     */
    kind?: string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningJob
     */
    type?: ProvisioningJobTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ProvisioningJob
     */
    vmid?: number;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningJob
     */
    node?: string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningJob
     */
    status?: ProvisioningJobStatusEnum;
    /**
     * Populated when status is failed.
     * @type {string}
     * @memberof ProvisioningJob
     */
    error?: string;
    /**
     * 
     * @type {number}
     * @memberof ProvisioningJob
     */
    attempts?: number;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningJob
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningJob
     */
    startedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ProvisioningJob
     */
    finishedAt?: string;
}


/**
 * @export
 */
export const ProvisioningJobTypeEnum = {
    Qemu: 'qemu',
    Lxc: 'lxc'
} as const;
export type ProvisioningJobTypeEnum = typeof ProvisioningJobTypeEnum[keyof typeof ProvisioningJobTypeEnum];

/**
 * @export
 */
export const ProvisioningJobStatusEnum = {
    Queued: 'queued',
    Running: 'running',
    Done: 'done',
    Failed: 'failed'
} as const;
export type ProvisioningJobStatusEnum = typeof ProvisioningJobStatusEnum[keyof typeof ProvisioningJobStatusEnum];


/**
 * Check if a given object implements the ProvisioningJob interface.
 */
export function instanceOfProvisioningJob(value: object): value is ProvisioningJob {
    return true;
}

export function ProvisioningJobFromJSON(json: any): ProvisioningJob {
    return ProvisioningJobFromJSONTyped(json, false);
}

export function ProvisioningJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProvisioningJob {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'type': json['type'] == null ? undefined : json['type'],
        'vmid': json['vmid'] == null ? undefined : json['vmid'],
        'node': json['node'] == null ? undefined : json['node'],
        'status': json['status'] == null ? undefined : json['status'],
        'error': json['error'] == null ? undefined : json['error'],
        'attempts': json['attempts'] == null ? undefined : json['attempts'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'startedAt': json['started_at'] == null ? undefined : json['started_at'],
        'finishedAt': json['finished_at'] == null ? undefined : json['finished_at'],
    };
}

export function ProvisioningJobToJSON(json: any): ProvisioningJob {
    return ProvisioningJobToJSONTyped(json, false);
}

export function ProvisioningJobToJSONTyped(value?: ProvisioningJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kind': value['kind'],
        'type': value['type'],
        'vmid': value['vmid'],
        'node': value['node'],
        'status': value['status'],
        'error': value['error'],
        'attempts': value['attempts'],
        'created_at': value['createdAt'],
        'started_at': value['startedAt'],
        'finished_at': value['finishedAt'],
    };
}

