/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReinstallGuestRequest
 */
export interface ReinstallGuestRequest {
    /**
     * The PVE node the guest currently lives on.
     * @type {string}
     * @memberof ReinstallGuestRequest
     */
    node: string;
    /**
     * `tpl:<id>` for QEMU, or a `vztmpl` volid for LXC.
     * @type {string}
     * @memberof ReinstallGuestRequest
     */
    osTemplate: string;
    /**
     * New root password, minimum 5 characters.
     * @type {string}
     * @memberof ReinstallGuestRequest
     */
    password?: string;
    /**
     * Public key bodies, merged with any owner-stored keys.
     * @type {Array<string>}
     * @memberof ReinstallGuestRequest
     */
    sshKeys?: Array<string>;
    /**
     * When set, the owner's stored SSH keys are merged into the reinstall (same as create).
     * @type {number}
     * @memberof ReinstallGuestRequest
     */
    ownerId?: number;
    /**
     * Optional new guest name.
     * @type {string}
     * @memberof ReinstallGuestRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the ReinstallGuestRequest interface.
 */
export function instanceOfReinstallGuestRequest(value: object): value is ReinstallGuestRequest {
    if (!('node' in value) || value['node'] === undefined) return false;
    if (!('osTemplate' in value) || value['osTemplate'] === undefined) return false;
    return true;
}

export function ReinstallGuestRequestFromJSON(json: any): ReinstallGuestRequest {
    return ReinstallGuestRequestFromJSONTyped(json, false);
}

export function ReinstallGuestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReinstallGuestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'node': json['node'],
        'osTemplate': json['os_template'],
        'password': json['password'] == null ? undefined : json['password'],
        'sshKeys': json['ssh_keys'] == null ? undefined : json['ssh_keys'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ReinstallGuestRequestToJSON(json: any): ReinstallGuestRequest {
    return ReinstallGuestRequestToJSONTyped(json, false);
}

export function ReinstallGuestRequestToJSONTyped(value?: ReinstallGuestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'node': value['node'],
        'os_template': value['osTemplate'],
        'password': value['password'],
        'ssh_keys': value['sshKeys'],
        'owner_id': value['ownerId'],
        'name': value['name'],
    };
}

