/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResellerPlan
 */
export interface ResellerPlan {
    /**
     * 
     * @type {string}
     * @memberof ResellerPlan
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ResellerPlan
     */
    description?: string;
    /**
     * 0 = unlimited.
     * @type {number}
     * @memberof ResellerPlan
     */
    maxCustomers?: number;
    /**
     * 0 = unlimited.
     * @type {number}
     * @memberof ResellerPlan
     */
    maxGuests?: number;
    /**
     * 0 = unlimited.
     * @type {number}
     * @memberof ResellerPlan
     */
    maxCores?: number;
    /**
     * 0 = unlimited.
     * @type {number}
     * @memberof ResellerPlan
     */
    maxMemoryMb?: number;
    /**
     * 0 = unlimited.
     * @type {number}
     * @memberof ResellerPlan
     */
    maxDiskGb?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ResellerPlan
     */
    isActive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResellerPlan
     */
    id?: number;
}

/**
 * Check if a given object implements the ResellerPlan interface.
 */
export function instanceOfResellerPlan(value: object): value is ResellerPlan {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ResellerPlanFromJSON(json: any): ResellerPlan {
    return ResellerPlanFromJSONTyped(json, false);
}

export function ResellerPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResellerPlan {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'maxCustomers': json['max_customers'] == null ? undefined : json['max_customers'],
        'maxGuests': json['max_guests'] == null ? undefined : json['max_guests'],
        'maxCores': json['max_cores'] == null ? undefined : json['max_cores'],
        'maxMemoryMb': json['max_memory_mb'] == null ? undefined : json['max_memory_mb'],
        'maxDiskGb': json['max_disk_gb'] == null ? undefined : json['max_disk_gb'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ResellerPlanToJSON(json: any): ResellerPlan {
    return ResellerPlanToJSONTyped(json, false);
}

export function ResellerPlanToJSONTyped(value?: ResellerPlan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'max_customers': value['maxCustomers'],
        'max_guests': value['maxGuests'],
        'max_cores': value['maxCores'],
        'max_memory_mb': value['maxMemoryMb'],
        'max_disk_gb': value['maxDiskGb'],
        'is_active': value['isActive'],
        'id': value['id'],
    };
}

