/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResellerSummary
 */
export interface ResellerSummary {
    /**
     * 
     * @type {number}
     * @memberof ResellerSummary
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ResellerSummary
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof ResellerSummary
     */
    email?: string;
    /**
     * 
     * @type {number}
     * @memberof ResellerSummary
     */
    isActive?: number;
    /**
     * Number of customers currently linked to this reseller.
     * @type {number}
     * @memberof ResellerSummary
     */
    customers?: number;
    /**
     * 
     * @type {string}
     * @memberof ResellerSummary
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the ResellerSummary interface.
 */
export function instanceOfResellerSummary(value: object): value is ResellerSummary {
    return true;
}

export function ResellerSummaryFromJSON(json: any): ResellerSummary {
    return ResellerSummaryFromJSONTyped(json, false);
}

export function ResellerSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResellerSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'customers': json['customers'] == null ? undefined : json['customers'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
    };
}

export function ResellerSummaryToJSON(json: any): ResellerSummary {
    return ResellerSummaryToJSONTyped(json, false);
}

export function ResellerSummaryToJSONTyped(value?: ResellerSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'is_active': value['isActive'],
        'customers': value['customers'],
        'created_at': value['createdAt'],
    };
}

