/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetGuestIpconfigRequest
 */
export interface SetGuestIpconfigRequest {
    /**
     * The PVE node the guest currently lives on.
     * @type {string}
     * @memberof SetGuestIpconfigRequest
     */
    node: string;
    /**
     * For example "ip=dhcp" or "ip=1.2.3.4/24,gw=1.2.3.1".
     * @type {string}
     * @memberof SetGuestIpconfigRequest
     */
    ipconfig: string;
    /**
     * Defaults to vmbr0.
     * @type {string}
     * @memberof SetGuestIpconfigRequest
     */
    bridge?: string;
}

/**
 * Check if a given object implements the SetGuestIpconfigRequest interface.
 */
export function instanceOfSetGuestIpconfigRequest(value: object): value is SetGuestIpconfigRequest {
    if (!('node' in value) || value['node'] === undefined) return false;
    if (!('ipconfig' in value) || value['ipconfig'] === undefined) return false;
    return true;
}

export function SetGuestIpconfigRequestFromJSON(json: any): SetGuestIpconfigRequest {
    return SetGuestIpconfigRequestFromJSONTyped(json, false);
}

export function SetGuestIpconfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetGuestIpconfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'node': json['node'],
        'ipconfig': json['ipconfig'],
        'bridge': json['bridge'] == null ? undefined : json['bridge'],
    };
}

export function SetGuestIpconfigRequestToJSON(json: any): SetGuestIpconfigRequest {
    return SetGuestIpconfigRequestToJSONTyped(json, false);
}

export function SetGuestIpconfigRequestToJSONTyped(value?: SetGuestIpconfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'node': value['node'],
        'ipconfig': value['ipconfig'],
        'bridge': value['bridge'],
    };
}

