/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetGuestFirewallOptionsRequest
 */
export interface SetGuestFirewallOptionsRequest {
    /**
     * 
     * @type {string}
     * @memberof SetGuestFirewallOptionsRequest
     */
    node: string;
    /**
     * 
     * @type {boolean}
     * @memberof SetGuestFirewallOptionsRequest
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SetGuestFirewallOptionsRequest
     */
    policyIn?: SetGuestFirewallOptionsRequestPolicyInEnum;
    /**
     * 
     * @type {string}
     * @memberof SetGuestFirewallOptionsRequest
     */
    policyOut?: SetGuestFirewallOptionsRequestPolicyOutEnum;
}


/**
 * @export
 */
export const SetGuestFirewallOptionsRequestPolicyInEnum = {
    Accept: 'ACCEPT',
    Drop: 'DROP',
    Reject: 'REJECT'
} as const;
export type SetGuestFirewallOptionsRequestPolicyInEnum = typeof SetGuestFirewallOptionsRequestPolicyInEnum[keyof typeof SetGuestFirewallOptionsRequestPolicyInEnum];

/**
 * @export
 */
export const SetGuestFirewallOptionsRequestPolicyOutEnum = {
    Accept: 'ACCEPT',
    Drop: 'DROP',
    Reject: 'REJECT'
} as const;
export type SetGuestFirewallOptionsRequestPolicyOutEnum = typeof SetGuestFirewallOptionsRequestPolicyOutEnum[keyof typeof SetGuestFirewallOptionsRequestPolicyOutEnum];


/**
 * Check if a given object implements the SetGuestFirewallOptionsRequest interface.
 */
export function instanceOfSetGuestFirewallOptionsRequest(value: object): value is SetGuestFirewallOptionsRequest {
    if (!('node' in value) || value['node'] === undefined) return false;
    return true;
}

export function SetGuestFirewallOptionsRequestFromJSON(json: any): SetGuestFirewallOptionsRequest {
    return SetGuestFirewallOptionsRequestFromJSONTyped(json, false);
}

export function SetGuestFirewallOptionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetGuestFirewallOptionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'node': json['node'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'policyIn': json['policy_in'] == null ? undefined : json['policy_in'],
        'policyOut': json['policy_out'] == null ? undefined : json['policy_out'],
    };
}

export function SetGuestFirewallOptionsRequestToJSON(json: any): SetGuestFirewallOptionsRequest {
    return SetGuestFirewallOptionsRequestToJSONTyped(json, false);
}

export function SetGuestFirewallOptionsRequestToJSONTyped(value?: SetGuestFirewallOptionsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'node': value['node'],
        'enabled': value['enabled'],
        'policy_in': value['policyIn'],
        'policy_out': value['policyOut'],
    };
}

