/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { SetGuestPassword200ResponseAllOfData } from './SetGuestPassword200ResponseAllOfData';
import {
    SetGuestPassword200ResponseAllOfDataFromJSON,
    SetGuestPassword200ResponseAllOfDataFromJSONTyped,
    SetGuestPassword200ResponseAllOfDataToJSON,
    SetGuestPassword200ResponseAllOfDataToJSONTyped,
} from './SetGuestPassword200ResponseAllOfData';

/**
 * 
 * @export
 * @interface SetGuestPassword200Response
 */
export interface SetGuestPassword200Response {
    /**
     * 
     * @type {boolean}
     * @memberof SetGuestPassword200Response
     */
    success: boolean;
    /**
     * 
     * @type {SetGuestPassword200ResponseAllOfData}
     * @memberof SetGuestPassword200Response
     */
    data: SetGuestPassword200ResponseAllOfData;
    /**
     * A human-readable error message, null on success.
     * @type {string}
     * @memberof SetGuestPassword200Response
     */
    error: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof SetGuestPassword200Response
     */
    meta?: PaginationMeta;
}

/**
 * Check if a given object implements the SetGuestPassword200Response interface.
 */
export function instanceOfSetGuestPassword200Response(value: object): value is SetGuestPassword200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function SetGuestPassword200ResponseFromJSON(json: any): SetGuestPassword200Response {
    return SetGuestPassword200ResponseFromJSONTyped(json, false);
}

export function SetGuestPassword200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetGuestPassword200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': SetGuestPassword200ResponseAllOfDataFromJSON(json['data']),
        'error': json['error'],
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    };
}

export function SetGuestPassword200ResponseToJSON(json: any): SetGuestPassword200Response {
    return SetGuestPassword200ResponseToJSONTyped(json, false);
}

export function SetGuestPassword200ResponseToJSONTyped(value?: SetGuestPassword200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SetGuestPassword200ResponseAllOfDataToJSON(value['data']),
        'error': value['error'],
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

