/* tslint:disable */
/* eslint-disable */
/**
 * NexoVirt REST API
 * A clean REST API over Proxmox VE, exposed by the NexoVirt panel at `/api/v1`.  Use it to discover placement (nodes, storages, networks), discover provisioning inputs (plans, OS templates, CT templates, IP zones, SSH keys), create QEMU VMs and LXC containers, run lifecycle actions (power, reinstall, password reset, IP config, delete), and poll asynchronous jobs and live PVE tasks to completion, all without touching the web UI.  ## Response envelope  Every response is JSON shaped as `{ success, data, error }`. On success, `success` is `true`, `data` holds the payload, and `error` is `null`. On failure, `success` is `false`, `data` is `null`, and `error` is a human-readable message, alongside a matching HTTP status code (`400`, `401`, `403`, `404`, `409`, `422`, `502`).  List endpoints that paginate add a `meta` object: `{ page, perPage, total }`. Request a page with `?page=<n>&perPage=<1..200>` (default `perPage` is 50, clamped to 200).  ## Authentication  Every request needs `Authorization: Bearer <token>`. Create tokens in the panel under Settings, API tokens. A token may be host-scoped (restricted to certain host ids), IP-allowlisted, and rate-limited. A scoped token gets `403 Forbidden` on any `/hosts/{id}/...` path it is not permitted to touch.  ## Content type  Send `Content-Type: application/json` for POST bodies. Form-encoded bodies also work.  ## Async guest creation  `POST /hosts/{id}/guests` enqueues a provisioning job and returns immediately with `{ queued: true, job_id, vmid }`. Poll `GET /hosts/{id}/jobs/{jobId}` until `data.status` reaches a terminal state, either `done` or `failed` (transitions through `queued` then `running`). On failure, `data.error` carries the reason. The same executor that backs the web wizard runs the actual PVE work. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@nexovirt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsageSeriesSeriesInner } from './UsageSeriesSeriesInner';
import {
    UsageSeriesSeriesInnerFromJSON,
    UsageSeriesSeriesInnerFromJSONTyped,
    UsageSeriesSeriesInnerToJSON,
    UsageSeriesSeriesInnerToJSONTyped,
} from './UsageSeriesSeriesInner';

/**
 * 
 * @export
 * @interface UsageSeries
 */
export interface UsageSeries {
    /**
     * 
     * @type {string}
     * @memberof UsageSeries
     */
    range?: UsageSeriesRangeEnum;
    /**
     * 
     * @type {Array<UsageSeriesSeriesInner>}
     * @memberof UsageSeries
     */
    series?: Array<UsageSeriesSeriesInner>;
}


/**
 * @export
 */
export const UsageSeriesRangeEnum = {
    _30m: '30m',
    _3h: '3h',
    _24h: '24h'
} as const;
export type UsageSeriesRangeEnum = typeof UsageSeriesRangeEnum[keyof typeof UsageSeriesRangeEnum];


/**
 * Check if a given object implements the UsageSeries interface.
 */
export function instanceOfUsageSeries(value: object): value is UsageSeries {
    return true;
}

export function UsageSeriesFromJSON(json: any): UsageSeries {
    return UsageSeriesFromJSONTyped(json, false);
}

export function UsageSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageSeries {
    if (json == null) {
        return json;
    }
    return {
        
        'range': json['range'] == null ? undefined : json['range'],
        'series': json['series'] == null ? undefined : ((json['series'] as Array<any>).map(UsageSeriesSeriesInnerFromJSON)),
    };
}

export function UsageSeriesToJSON(json: any): UsageSeries {
    return UsageSeriesToJSONTyped(json, false);
}

export function UsageSeriesToJSONTyped(value?: UsageSeries | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'range': value['range'],
        'series': value['series'] == null ? undefined : ((value['series'] as Array<any>).map(UsageSeriesSeriesInnerToJSON)),
    };
}

